(()=>{
  const $=id=>document.getElementById(id),stage=$("stage"),toggle=$("audioToggle");
  class Sound{
    constructor(){this.ctx=null;this.master=null;this.music=null;this.fx=null;this.filter=null;this.started=false;this.tension=0;try{this.muted=localStorage.getItem("heist_muted")==="1"}catch{this.muted=false}}
    async unlock(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C;this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.fx=this.ctx.createGain();this.filter=this.ctx.createBiquadFilter();this.filter.type="lowpass";this.filter.frequency.value=620;this.music.gain.value=.1;this.fx.gain.value=.5;this.music.connect(this.filter);this.filter.connect(this.master);this.fx.connect(this.master);this.master.connect(this.ctx.destination);this.apply()}if(this.ctx.state==="suspended")await this.ctx.resume();if(!this.started)this.start()}
    apply(){if(this.master&&this.ctx)this.master.gain.setTargetAtTime(this.muted?0:.62,this.ctx.currentTime,.03);if(toggle){toggle.textContent=this.muted?"🔇":"🔊";toggle.classList.toggle("muted",this.muted)}}
    toggle(){this.muted=!this.muted;try{localStorage.setItem("heist_muted",this.muted?"1":"0")}catch{}this.apply();if(!this.muted)this.play("click")}
    tone(f,d=.12,type="sine",v=.06,delay=0,end=null,bus=null){if(!this.ctx||this.muted)return;const n=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,n);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(1,end),n+d);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(v,n+.012);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(bus||this.fx);o.start(n);o.stop(n+d+.03)}
    noise(d=.16,v=.04,cut=800){if(!this.ctx||this.muted)return;const len=Math.floor(this.ctx.sampleRate*d),b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(1-i/len);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=cut;g.gain.value=v;s.buffer=b;s.connect(f);f.connect(g);g.connect(this.fx);s.start()}
    start(){this.started=true;const a=this.ctx.createOscillator(),b=this.ctx.createOscillator(),ga=this.ctx.createGain(),gb=this.ctx.createGain(),l=this.ctx.createOscillator(),lg=this.ctx.createGain();a.type="sine";a.frequency.value=55;b.type="triangle";b.frequency.value=82.41;ga.gain.value=.06;gb.gain.value=.026;l.frequency.value=.07;lg.gain.value=.012;l.connect(lg);lg.connect(ga.gain);a.connect(ga);b.connect(gb);ga.connect(this.music);gb.connect(this.music);a.start();b.start();l.start();setInterval(()=>{if(!this.ctx||this.muted)return;const s=this.tension>.6?[110,123.47,138.59,164.81]:[82.41,98,110,123.47],f=s[Math.floor(Math.random()*s.length)];this.tone(f,.85,"sine",.012+this.tension*.015,0,f*.995,this.music)},1800)}
    setTension(v){this.tension=Math.max(0,Math.min(1,v));if(this.filter&&this.ctx)this.filter.frequency.setTargetAtTime(520+this.tension*1050,this.ctx.currentTime,.18)}
    play(n){if(n==="click")this.tone(260,.045,"square",.03,0,210);else if(n==="pin"){this.tone(720,.07,"triangle",.05);this.tone(980,.05,"sine",.025,.035)}else if(n==="near")this.tone(520,.07,"sine",.025);else if(n==="error"){this.tone(180,.18,"sawtooth",.06,0,92);this.noise(.15,.03,520)}else if(n==="success"){this.tone(620,.12,"triangle",.06);this.tone(830,.18,"triangle",.055,.08);this.tone(1120,.25,"sine",.04,.16)}else if(n==="vault"){this.tone(92,.34,"sawtooth",.08,0,54);this.noise(.3,.05,420);this.tone(440,.24,"triangle",.04,.18,660)}else if(n==="coin"){this.tone(980,.08,"triangle",.05);this.tone(1320,.15,"sine",.04,.07)}else if(n==="alarm"){this.tone(740,.18,"square",.05);this.tone(570,.2,"square",.045,.19)}else if(n==="smoke"){this.noise(.52,.06,1250);this.tone(120,.4,"sine",.024)}else if(n==="zone"){this.tone(330,.28,"sine",.024);this.tone(495,.34,"sine",.018,.09)}else if(n==="finish"){this.tone(392,.18,"triangle",.05);this.tone(523,.25,"triangle",.05,.12);this.tone(659,.36,"sine",.04,.24)}}
  }
  const sound=new Sound;sound.apply();
  const unlock=()=>sound.unlock();document.addEventListener("pointerdown",unlock,{once:true,capture:true});document.addEventListener("click",e=>{unlock();if(e.target.closest("button")&&!e.target.closest("#audioToggle"))sound.play("click")},true);toggle?.addEventListener("click",async()=>{await sound.unlock();sound.toggle()});
  let oldLoot=$("loot")?.textContent||"0",oldAlarm=0,crackOpen=false,smokeOpen=false,oldZone="",resultOpen=false;
  const observeText=(el,fn)=>el&&new MutationObserver(fn).observe(el,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:["class","style"]});
  observeText($("loot"),()=>{const v=$("loot").textContent;if(v!==oldLoot&&Number(v)>Number(oldLoot))sound.play("coin");oldLoot=v});
  observeText($("alarmText"),()=>{const v=parseInt($("alarmText").textContent)||0;sound.setTension(v/100);if(v>=60&&oldAlarm<60||v>=85&&oldAlarm<85)sound.play("alarm");oldAlarm=v});
  observeText($("crackOverlay"),()=>{const open=!$("crackOverlay").classList.contains("hidden");if(open&&!crackOpen)sound.play("vault");crackOpen=open});
  observeText($("crackMessage"),()=>{const m=$("crackMessage");if(m.classList.contains("success"))sound.play("success");else if(m.classList.contains("error"))sound.play("error")});
  observeText($("zoneBanner"),()=>{const z=$("zoneBanner").textContent;if(z&&z!==oldZone){oldZone=z;sound.play("zone");syncZone(z)}});
  observeText($("smokeStatus"),()=>{const open=!$("smokeStatus").classList.contains("hidden");if(open&&!smokeOpen)sound.play("smoke");smokeOpen=open});
  observeText($("finish"),()=>{const open=!$("finish").classList.contains("hidden");if(open&&!resultOpen)sound.play("finish");resultOpen=open});
  observeText($("crackGame"),()=>{const dial=$("dialTap");if(dial&&!dial.dataset.heistSound){dial.dataset.heistSound="1";dial.addEventListener("click",()=>sound.play("pin"))}document.querySelectorAll(".pinColumn:not([data-heist-sound])").forEach(p=>{p.dataset.heistSound="1";p.addEventListener("click",()=>sound.play("pin"))});const h=$("sweetHint");if(h&&!h.dataset.heistWatch){h.dataset.heistWatch="1";new MutationObserver(()=>{if(h.textContent.includes("ОСЛАБ"))sound.play("near")}).observe(h,{childList:true,subtree:true,characterData:true})}});
  setInterval(()=>{const d=$("dialTap"),needle=$("dialNeedle"),target=$("dialTarget");if(!d||!needle||!target)return;const n=getComputedStyle(needle).transform;d.classList.toggle("heist-near",n&&n!=="none")},150);

  const atmo=document.createElement("canvas");atmo.className="heistAtmo";stage.prepend(atmo);const ac=atmo.getContext("2d"),particles=[];let zone="broken",last=performance.now(),dpr=1;
  function size(){const r=stage.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);atmo.width=Math.max(1,Math.round(r.width*dpr));atmo.height=Math.max(1,Math.round(r.height*dpr));atmo.style.width=`${r.width}px`;atmo.style.height=`${r.height}px`};new ResizeObserver(size).observe(stage);size();
  function syncZone(text){zone=text.includes("ЗОЛОТО")?"gold":text.includes("ТЕХНИ")?"tech":text.includes("ОХРАН")?"security":text.includes("ЛАЗЕР")?"laser":"broken";stage.classList.remove("atmo-gold","atmo-tech","atmo-security","atmo-laser","atmo-broken");stage.classList.add(`atmo-${zone}`)}syncZone($("zoneBanner")?.textContent||"");
  function spawn(w,h){const colors={gold:"255,215,108",tech:"112,217,232",security:"255,111,139",laser:"255,69,95",broken:"169,149,214"},count=zone==="broken"?2:1;for(let i=0;i<count;i++)particles.push({x:Math.random()*w,y:126+Math.random()*Math.max(1,h-150),vx:(Math.random()-.5)*8,vy:zone==="broken"?-8-Math.random()*10:-3-Math.random()*7,r:1+Math.random()*2,life:2+Math.random()*3,c:colors[zone]})}
  function drawAtmo(now){const w=atmo.width/dpr,h=atmo.height/dpr,dt=Math.min(.05,(now-last)/1000);last=now;ac.setTransform(dpr,0,0,dpr,0,0);ac.clearRect(0,0,w,h);ac.save();ac.beginPath();ac.rect(0,126,w,h-126);ac.clip();if(Math.random()<dt*9)spawn(w,h);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;ac.fillStyle=`rgba(${p.c},${Math.max(0,Math.min(.24,p.life*.07))})`;ac.shadowBlur=zone==="laser"||zone==="gold"?8:0;ac.shadowColor=`rgb(${p.c})`;ac.beginPath();ac.arc(p.x,p.y,p.r,0,Math.PI*2);ac.fill()}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0||particles[i].y<120)particles.splice(i,1);ac.shadowBlur=0;const t=now/1000;if(zone==="gold"){ac.strokeStyle=`rgba(255,215,108,${.035+.025*Math.sin(t)})`;for(let x=40;x<w;x+=95){ac.strokeRect(x,150,38,54);ac.beginPath();ac.arc(x+19,177,8,0,Math.PI*2);ac.stroke()}}else if(zone==="tech"){ac.strokeStyle="rgba(112,217,232,.055)";for(let y=150;y<h;y+=36){ac.beginPath();ac.moveTo(0,y);ac.lineTo(w,y);ac.stroke()}ac.fillStyle=`rgba(112,217,232,${.025+.025*Math.sin(t*2)})`;ac.fillRect(0,126+(t*35%(Math.max(1,h-126))),w,2)}else if(zone==="security"){ac.strokeStyle="rgba(255,111,139,.055)";for(let x=28;x<w;x+=110)for(let y=160;y<h;y+=100)ac.strokeRect(x,y,55,28);ac.fillStyle=`rgba(255,111,139,${.03+.025*Math.sin(t*3)})`;ac.fillRect((t*45)%w,126,2,h-126)}else if(zone==="laser"){ac.strokeStyle=`rgba(255,69,95,${.05+.04*Math.sin(t*4)})`;ac.shadowBlur=10;ac.shadowColor="#ff455f";for(let y=170;y<h;y+=95){ac.beginPath();ac.moveTo(0,y);ac.lineTo(w,y-28);ac.stroke()}ac.shadowBlur=0}else{ac.strokeStyle="rgba(169,149,214,.07)";for(let x=20;x<w;x+=90){ac.beginPath();ac.moveTo(x,145);ac.lineTo(x+22,185);ac.lineTo(x+8,220);ac.lineTo(x+35,255);ac.stroke()}}ac.restore();requestAnimationFrame(drawAtmo)}requestAnimationFrame(drawAtmo);
})();
