(()=>{
"use strict";
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor?.("#08070c");tg?.setBackgroundColor?.("#08070c");
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),chatId=params.get("chat_id")||"",initData=tg?.initData||"",headers={"Content-Type":"application/json","X-Telegram-Init-Data":initData};
const canvas=$("game"),ctx=canvas.getContext("2d"),miniCanvas=$("miniMap"),mini=miniCanvas.getContext("2d"),stage=$("stage"),fx=document.body;
const CELL=88,COLS=12,ROWS=18,WORLD_W=COLS*CELL,WORLD_H=ROWS*CELL,WALL=10,START={c:0,r:ROWS-1};
const ZONES=["gold","tech","security","laser","broken"],ZONE={
 gold:{name:"ЗОЛОТОЙ СЕКТОР",floor:"#211713",line:"#805526",accent:"#ffd76c",decor:["display","goldPile","portrait","crate","seal"],bonus:1.18},
 tech:{name:"ТЕХНИЧЕСКИЙ СЕКТОР",floor:"#0d171a",line:"#24515a",accent:"#70d9e8",decor:["server","cable","vent","panel","coil"],bonus:1},
 security:{name:"ПОСТ ОХРАНЫ",floor:"#181015",line:"#623044",accent:"#ff6f8b",decor:["monitor","desk","cameraRack","stripe","panel"],bonus:1.05},
 laser:{name:"ЛАЗЕРНЫЙ СЕКТОР",floor:"#180e11",line:"#70232c",accent:"#ff455f",decor:["laser","warning","emitter","vent","stripe"],bonus:1.25},
 broken:{name:"АВАРИЙНЫЙ СЕКТОР",floor:"#141318",line:"#423d52",accent:"#a995d6",decor:["crack","rubble","cable","sparks","vent"],bonus:1.08}
};
const SAFE={1:{name:"МЕХАНИЧЕСКИЙ СЕЙФ",label:"ОБЫЧНЫЙ",color:"#ffd76c",method:"lockpick",difficulty:"НИЗКАЯ",size:27,base:[24,44]},2:{name:"ШТИФТОВЫЙ СЕЙФ",label:"УСИЛЕННЫЙ",color:"#70d9e8",method:"pins",difficulty:"СРЕДНЯЯ",size:29,base:[42,68]},3:{name:"КОДОВЫЙ СЕЙФ",label:"ЭЛИТНЫЙ",color:"#d986ff",method:"dial",difficulty:"ВЫСОКАЯ",size:31,base:[68,108]},4:{name:"ГЛАВНОЕ ХРАНИЛИЩЕ",label:"ЛЕГЕНДАРНЫЙ",color:"#ffe28c",method:"master",difficulty:"МАКСИМАЛЬНАЯ",size:36,base:[130,190]}};
const LOADOUTS={silent:{name:"ТИХИЙ",smoke:3,emp:0,alarmMult:.72,hackSpeed:.92,durability:105,dialBonus:9,terminalSpeed:1},pro:{name:"ПРОФИ",smoke:2,emp:1,alarmMult:.9,hackSpeed:1.08,durability:130,dialBonus:6,terminalSpeed:1.5},aggressive:{name:"ШТУРМ",smoke:1,emp:2,alarmMult:1.22,hackSpeed:1.35,durability:95,dialBonus:3,terminalSpeed:1.1}};
const MISSIONS=[
 {id:"loot",title:"Вынести крупную сумму",desc:"Собери не менее 420 влияния",goal:420},
 {id:"elite",title:"Элитная цель",desc:"Вскрой элитный сейф",goal:1},
 {id:"stealth",title:"Тихая операция",desc:"Уйди, не поднимая тревогу выше 35%",goal:35},
 {id:"perfect",title:"Работа мастера",desc:"Сделай 3 идеальных взлома",goal:3},
 {id:"secret",title:"Секретные документы",desc:"Найди 2 тайника",goal:2}
];
let dpr=1,viewW=400,viewH=620,hudSafe=124,rng=Math.random,seed=1,mapCode="—",sessionId="",demo=false;
let cells=[],walls=[],safes=[],cameras=[],decor=[],terminals=[],vents=[],covers=[],secrets=[],lasers=[],particles=[],floaters=[],trails=[],route=[],discovered=new Set();
let running=false,ended=false,duration=210,timeLeft=210,startedAt=0,lastFrame=0,loot=0,secured=0,alarm=0,maxAlarm=0,opened=0,totalSafes=0,perfect=0,secretsGot=0,missionComplete=false;
let phase="infiltration",currentZone="",zoneTimer=0,bannerTimer=0,phaseTimer=0,smokeTime=0,cameraDisabled=0,moveX=0,moveY=0,shake=0,idleTime=0,selectedLoadout="silent",gadget={smoke:3,emp:0},tutorialStep=0,tutorialActive=false;
let camera={x:0,y:0},exit={x:14,y:WORLD_H-76,w:60,h:60},player={x:CELL/2,y:WORLD_H-CELL/2,r:10.5,vx:0,vy:0,stretch:0,bump:0,angle:0,hidden:false,bag:0};
let mission=MISSIONS[0],crack={active:false},profile=loadProfile();
function loadProfile(){try{return Object.assign({xp:0,level:1,runs:0,best:0,tutorial:false},JSON.parse(localStorage.getItem("heist_profile_v84")||"{}"))}catch{return{xp:0,level:1,runs:0,best:0,tutorial:false}}}
function saveProfile(){try{localStorage.setItem("heist_profile_v84",JSON.stringify(profile))}catch{}}
function seeded(v){let s=(Number(v)||1)>>>0;return()=>((s=Math.imul(s,1664525)+1013904223>>>0)/4294967296)}
const rand=(a,b)=>a+(b-a)*rng(),randInt=(a,b)=>Math.floor(rand(a,b+1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),idx=(c,r)=>r*COLS+c,cellAt=(c,r)=>c>=0&&r>=0&&c<COLS&&r<ROWS?cells[idx(c,r)]:null,center=(c,r)=>({x:c*CELL+CELL/2,y:r*CELL+CELL/2}),key=(c,r)=>`${c}:${r}`,manhattan=(a,b)=>Math.abs(a.c-b.c)+Math.abs(a.r-b.r),degDiff=(a,b)=>Math.abs((((a-b)+540)%360)-180),norm=a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function zoneFor(c,r){if(r<4)return c<4?"gold":c<8?"tech":"security";if(r<9)return c<4?"security":c<8?"tech":"laser";if(r<14)return c<4?"gold":c<8?"broken":"laser";return c<4?"broken":c<8?"security":"gold"}
function buildMaze(){cells=Array.from({length:COLS*ROWS},(_,i)=>({c:i%COLS,r:Math.floor(i/COLS),n:1,e:1,s:1,w:1,seen:false,zone:zoneFor(i%COLS,Math.floor(i/COLS))}));const stack=[cellAt(START.c,START.r)];stack[0].seen=true;while(stack.length){const cur=stack[stack.length-1],nexts=[];for(const [dc,dr,side,back] of [[0,-1,"n","s"],[1,0,"e","w"],[0,1,"s","n"],[-1,0,"w","e"]]){const n=cellAt(cur.c+dc,cur.r+dr);if(n&&!n.seen)nexts.push([n,side,back])}if(!nexts.length){stack.pop();continue}const [n,side,back]=nexts[Math.floor(rng()*nexts.length)];cur[side]=0;n[back]=0;n.seen=true;stack.push(n)}
 for(let i=0;i<34;i++){const c=randInt(1,COLS-2),r=randInt(1,ROWS-2),a=cellAt(c,r);if(rng()<.5){const b=cellAt(c+1,r);a.e=0;b.w=0}else{const b=cellAt(c,r+1);a.s=0;b.n=0}}
 walls=[];for(const c of cells){const x=c.c*CELL,y=c.r*CELL;if(c.n)walls.push({x,y,w:CELL,h:WALL});if(c.w)walls.push({x,y,w:WALL,h:CELL});if(c.r===ROWS-1&&c.s)walls.push({x,y:y+CELL-WALL,w:CELL,h:WALL});if(c.c===COLS-1&&c.e)walls.push({x:x+CELL-WALL,y,w:WALL,h:CELL})}}
function openCells(){return cells.filter(c=>!(c.c===START.c&&c.r===START.r))}
function farCells(min=8){return openCells().filter(c=>manhattan(c,START)>=min)}
function buildObjects(){safes=[];cameras=[];decor=[];terminals=[];vents=[];covers=[];secrets=[];lasers=[];particles=[];floaters=[];trails=[];discovered=new Set();reveal(START.c,START.r,1);
 const pool=shuffle(farCells(3));const main=farCells(18).sort((a,b)=>manhattan(b,START)-manhattan(a,START))[0]||pool[0];spawnSafe(main,4);const count=12;for(let i=0;i<count;i++){const c=pool.find(x=>!safes.some(s=>s.c===x.c&&s.r===x.r));if(!c)break;const tier=i<6?1:i<10?2:3;spawnSafe(c,tier)}totalSafes=safes.length;
 const camCells=shuffle(openCells().filter(c=>["security","laser","tech"].includes(c.zone)&&manhattan(c,START)>3)).slice(0,13);camCells.forEach((c,i)=>{const p=center(c.c,c.r);cameras.push({id:i,c:c.c,r:c.r,x:p.x+rand(-18,18),y:p.y+rand(-18,18),angle:rand(0,Math.PI*2),speed:rand(.28,.55)*(rng()<.5?-1:1),range:rand(155,215),fov:rand(.55,.78),alert:0,state:"search",pause:rand(0,.8)})});
 const termCells=shuffle(openCells().filter(c=>["tech","security"].includes(c.zone))).slice(0,4);termCells.forEach((c,i)=>{const p=center(c.c,c.r);terminals.push({id:i,c:c.c,r:c.r,x:p.x+rand(-20,20),y:p.y+rand(-18,18),used:false,type:i%2?"disable":"reveal"})});
 const ventCells=shuffle(openCells().filter(c=>["tech","broken"].includes(c.zone))).slice(0,4);for(let i=0;i<ventCells.length;i++){const c=ventCells[i],p=center(c.c,c.r);vents.push({id:i,c:c.c,r:c.r,x:p.x+rand(-15,15),y:p.y+rand(-15,15),pair:i%2===0?i+1:i-1})}
 shuffle(openCells().filter(c=>["security","broken","gold"].includes(c.zone))).slice(0,9).forEach((c,i)=>{const p=center(c.c,c.r);covers.push({id:i,c:c.c,r:c.r,x:p.x+rand(-20,20),y:p.y+rand(-20,20),r:24})});
 shuffle(openCells().filter(c=>manhattan(c,START)>6)).slice(0,2).forEach((c,i)=>{const p=center(c.c,c.r);secrets.push({id:i,c:c.c,r:c.r,x:p.x+rand(-16,16),y:p.y+rand(-16,16),found:false})});
 for(const c of cells){const p=center(c.c,c.r),types=ZONE[c.zone].decor;for(let i=0;i<(rng()<.34?2:1);i++)decor.push({x:p.x+rand(-31,31),y:p.y+rand(-31,31),rot:rand(-.8,.8),zone:c.zone,type:types[randInt(0,types.length-1)],pulse:rand(0,10)});if(c.zone==="laser"&&rng()<.22)lasers.push({c:c.c,r:c.r,x:p.x,y:p.y,angle:rng()<.5?0:Math.PI/2,length:CELL-18,active:true,phase:rand(0,6)})}
 player={x:CELL/2,y:WORLD_H-CELL/2,r:10.5,vx:0,vy:0,stretch:0,bump:0,angle:0,hidden:false,bag:0};camera={x:0,y:Math.max(0,WORLD_H-(viewH-hudSafe))};exit={x:14,y:WORLD_H-76,w:60,h:60};mapCode=String(seed>>>0).slice(-4).padStart(4,"0");route=[];currentZone=""}
function spawnSafe(c,tier){const p=center(c.c,c.r),m=SAFE[tier],v=Math.round(rand(m.base[0],m.base[1])*ZONE[c.zone].bonus);safes.push({id:safes.length,c:c.c,r:c.r,x:p.x+rand(-13,13),y:p.y+rand(-13,13),tier,value:v,opened:false,lockUntil:0,grade:null})}
function reveal(c,r,rad){for(let y=r-rad;y<=r+rad;y++)for(let x=c-rad;x<=c+rad;x++)if(cellAt(x,y))discovered.add(key(x,y))}
function playerCell(){return cellAt(clamp(Math.floor(player.x/CELL),0,COLS-1),clamp(Math.floor(player.y/CELL),0,ROWS-1))}
function neighbors(c){const out=[];if(!c.n)out.push(cellAt(c.c,c.r-1));if(!c.e)out.push(cellAt(c.c+1,c.r));if(!c.s)out.push(cellAt(c.c,c.r+1));if(!c.w)out.push(cellAt(c.c-1,c.r));return out.filter(Boolean)}
function findPath(from,to){if(!from||!to)return[];const q=[from],prev=new Map([[key(from.c,from.r),null]]);while(q.length){const cur=q.shift();if(cur===to)break;for(const n of neighbors(cur)){const k=key(n.c,n.r);if(prev.has(k))continue;prev.set(k,cur);q.push(n)}}if(!prev.has(key(to.c,to.r)))return[];const p=[];let cur=to;while(cur){p.push(center(cur.c,cur.r));cur=prev.get(key(cur.c,cur.r))}return p.reverse()}
function pointInWall(x,y,r=player.r){return x-r<0||y-r<0||x+r>WORLD_W||y+r>WORLD_H||walls.some(w=>x+r>w.x&&x-r<w.x+w.w&&y+r>w.y&&y-r<w.y+w.h)}
function pointHitsWall(x,y){if(x<0||y<0||x>=WORLD_W||y>=WORLD_H)return true;const c=Math.floor(x/CELL),r=Math.floor(y/CELL),cell=cellAt(c,r),lx=x-c*CELL,ly=y-r*CELL;if(!cell)return true;return(cell.n&&ly<WALL)||(cell.s&&ly>CELL-WALL)||(cell.w&&lx<WALL)||(cell.e&&lx>CELL-WALL)}
function segmentBlocked(x1,y1,x2,y2){const d=Math.hypot(x2-x1,y2-y1),n=Math.max(2,Math.ceil(d/5));for(let i=2;i<n-1;i++){const t=i/n;if(pointHitsWall(x1+(x2-x1)*t,y1+(y2-y1)*t))return true}return false}
function rayDistance(x,y,a,max){for(let d=7;d<=max;d+=6)if(pointHitsWall(x+Math.cos(a)*d,y+Math.sin(a)*d))return d-5;return max}
function nearest(list,limit,filter=()=>true){let best=null,d=Infinity;for(const o of list){if(!filter(o))continue;const v=Math.hypot(player.x-o.x,player.y-o.y);if(v<d){d=v;best=o}}return d<=limit?best:null}
function nearExit(){return player.x>exit.x-18&&player.x<exit.x+exit.w+18&&player.y>exit.y-18&&player.y<exit.y+exit.h+18}
function api(path,body={}){return fetch(`/games/api/${path}`,{method:"POST",headers,body:JSON.stringify({...body,chat_id:chatId})}).then(async r=>{const d=await r.json().catch(()=>({ok:false,reason:"Сервер не ответил"}));if(!r.ok||!d.ok)throw new Error(d.reason||"Ошибка сервера");return d})}
class AudioEngine{constructor(){this.ctx=null;this.master=null;this.music=null;this.fx=null;try{this.muted=localStorage.getItem("heist_muted")==="1"}catch{this.muted=false}this.started=false;this.step=0}async unlock(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C;this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.fx=this.ctx.createGain();this.music.connect(this.master);this.fx.connect(this.master);this.master.connect(this.ctx.destination);this.music.gain.value=.09;this.fx.gain.value=.42;this.apply()}if(this.ctx.state==="suspended")await this.ctx.resume();if(!this.started){this.started=true;this.loop()}}apply(){if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.7,this.ctx.currentTime,.03);$("soundToggle").textContent=this.muted?"🔇":"🔊";$("soundToggle").classList.toggle("muted",this.muted)}toggle(){this.muted=!this.muted;localStorage.setItem("heist_muted",this.muted?"1":"0");this.apply()}tone(f,d=.12,type="sine",v=.06,end=null,delay=0){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(1,end),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(this.fx);o.start(t);o.stop(t+d+.03)}sfx(n){if(n==="click")this.tone(320,.06,"square",.035,250);if(n==="safe")for(let i=0;i<3;i++)this.tone([330,440,660][i],.22,"sine",.07,null,i*.08);if(n==="error")this.tone(170,.2,"sawtooth",.08,80);if(n==="alarm")this.tone(620,.18,"square",.07,340);if(n==="pin")this.tone(820,.045,"square",.035,610);if(n==="perfect")for(let i=0;i<4;i++)this.tone([523,659,784,1046][i],.16,"triangle",.055,null,i*.07);if(n==="smoke")this.tone(130,.35,"sawtooth",.05,45);if(n==="emp")this.tone(1200,.25,"square",.05,100);if(n==="secret")for(let i=0;i<3;i++)this.tone([700,930,1200][i],.15,"sine",.05,null,i*.08)}loop(){if(!this.started)return;const tension=phase==="escape"?1:alarm/100,notes=[110,146.8,164.8,196],f=notes[this.step++%notes.length]*(tension>.6?2:1);this.tone(f,.48,"triangle",.018+tension*.012,null,0);if(this.step%4===0)this.tone(55,.8,"sine",.025+tension*.02,null,0);setTimeout(()=>this.loop(),phase==="escape"?330:520)}}
const audio=new AudioEngine();addEventListener("pointerdown",()=>audio.unlock(),{once:true});
function pickMission(){mission=MISSIONS[randInt(0,MISSIONS.length-1)];$("missionPreview").textContent=mission.desc}
function updateProfileCard(){const need=100+profile.level*65,within=profile.xp%need;$("profileLevel").textContent=profile.level;$("profileXp").style.width=`${clamp(within/need*100,0,100)}%`;const bonus=profile.level>=5?"+10% награды · +8 прочности":profile.level>=3?"+5% награды · +5 прочности":profile.level>=2?"+3 прочности инструмента":"Без постоянных бонусов";$("profileBonus").textContent=bonus}
function setPhase(next){if(phase===next)return;phase=next;const label=next==="infiltration"?"ПРОНИКНОВЕНИЕ":next==="heist"?"ОГРАБЛЕНИЕ":"ПОБЕГ";$("phaseLabel").textContent=label;$("phaseFlash").textContent=label;$("phaseFlash").classList.remove("show");void $("phaseFlash").offsetWidth;$("phaseFlash").classList.add("show");stage.classList.toggle("escape",next==="escape");audio.sfx(next==="escape"?"alarm":"click");if(next==="escape"){setHint("Выход отмечен зелёным. Охрана усилила наблюдение!",true);advanceTutorial(3)}}
function missionValue(){if(mission.id==="loot")return loot;if(mission.id==="elite")return safes.some(s=>s.tier>=3&&s.opened)?1:0;if(mission.id==="stealth")return maxAlarm<=mission.goal?mission.goal:maxAlarm;if(mission.id==="perfect")return perfect;if(mission.id==="secret")return secretsGot;return 0}
function updateMission(){let v=missionValue(),pct=0;if(mission.id==="stealth"){missionComplete=maxAlarm<=mission.goal&&phase==="escape";pct=clamp((mission.goal-maxAlarm)/mission.goal*100,0,100)}else{missionComplete=v>=mission.goal;pct=clamp(v/mission.goal*100,0,100)}$("missionLabel").textContent=mission.desc;$("missionProgress").style.width=`${pct}%`;if(missionComplete&&phase!=="escape")setPhase("escape")}
async function startGame(){audio.unlock();$("start").disabled=true;$("start").textContent="СОЗДАЁМ ХРАНИЛИЩЕ…";$("startError").textContent="";try{const d=await api("start",{game:"heist"});sessionId=d.session_id;seed=Number(d.seed)||Date.now();duration=Math.max(210,Number(d.duration)||0);demo=false}catch(e){if(initData){$("startError").textContent=e.message;$("start").disabled=false;$("start").textContent="ПОПРОБОВАТЬ СНОВА";return}sessionId="";seed=Date.now()>>>0;duration=210;demo=true;$("startError").textContent=`Демонстрационный режим: ${e.message}`}
 rng=seeded(seed);buildMaze();buildObjects();const kit=LOADOUTS[selectedLoadout];gadget={smoke:kit.smoke,emp:kit.emp};running=true;ended=false;timeLeft=duration;startedAt=performance.now();lastFrame=startedAt;loot=secured=alarm=maxAlarm=opened=perfect=secretsGot=0;missionComplete=false;phase="infiltration";smokeTime=cameraDisabled=shake=idleTime=0;$("phaseLabel").textContent="ПРОНИКНОВЕНИЕ";$("loot").textContent="0";$("finish").classList.add("hidden");$("intro").classList.add("hidden");$("mapCode").textContent=`КАРТА ${mapCode}`;$("safes").textContent=`СЕЙФЫ 0/${totalSafes}`;updateMission();updateGadgets();setHint("Найди первый сейф и начни ограбление",true);if(!profile.tutorial){tutorialActive=true;tutorialStep=0;showTutorial()}requestAnimationFrame(loop);$("start").disabled=false;$("start").textContent="НАЧАТЬ ОПЕРАЦИЮ"}
function setHint(t,pop=false){const h=$("hint");h.textContent=t;if(pop){h.classList.remove("pop");void h.offsetWidth;h.classList.add("pop")}}
function banner(t,s=1.4){$("alertBanner").textContent=t;$("alertBanner").classList.add("show");bannerTimer=s}
function showTutorial(){if(!tutorialActive)return;const steps=[["Дойди до сейфа","Используй большой джойстик. Жёлтые и фиолетовые объекты — цели."],["Вскрой сейф","Подойди ближе и нажми большую кнопку действия."],["Скройся от камеры","Стены и укрытия блокируют обзор. Дым мгновенно скрывает героя."],["Вернись к выходу","После выполнения задания начинается фаза побега."]],s=steps[tutorialStep]||steps[3];$("tutorialTitle").textContent=s[0];$("tutorialText").textContent=s[1];$("tutorial").classList.remove("hidden")}
function advanceTutorial(n){if(!tutorialActive||n!==tutorialStep)return;tutorialStep++;if(tutorialStep>=4){tutorialActive=false;profile.tutorial=true;saveProfile();$("tutorial").classList.add("hidden")}else showTutorial()}
function abortTutorial(){tutorialActive=false;profile.tutorial=true;saveProfile();$("tutorial").classList.add("hidden")}
function openCrack(safe){if(crack.active)return;const meta=SAFE[safe.tier],kit=LOADOUTS[selectedLoadout],bonus=(profile.level>=2?3:0)+(profile.level>=5?5:0);crack={active:true,safe,mode:meta.method,stages:meta.method==="master"?["lockpick","pins","dial"]:[meta.method],stageIndex:0,durability:kit.durability+bonus,errors:0,started:performance.now(),progress:0,turning:false,resolving:false,failed:false};stage.classList.add("cracking");const p=screen(safe.x,safe.y);stage.style.setProperty("--focus-x",`${p.x}px`);stage.style.setProperty("--focus-y",`${p.y}px`);$("crackPanel").className=`crackPanel tier${safe.tier}`;$("crackType").textContent=meta.name;$("crackDifficulty").textContent=`СЛОЖНОСТЬ: ${meta.difficulty}`;$("crackOverlay").classList.remove("hidden");renderCrack();audio.sfx("click");advanceTutorial(1)}
function closeCrack(){crack.active=false;$("crackOverlay").classList.add("hidden");stage.classList.remove("cracking");lastFrame=performance.now()}
function abortCrack(){if(!crack.active)return;alarm=clamp(alarm+3*LOADOUTS[selectedLoadout].alarmMult,0,100);crack.safe.lockUntil=performance.now()+1800;setHint("Взлом отменён. Система заметила вмешательство.",true);audio.sfx("error");closeCrack()}
function crackError(amount,msg){if(crack.failed||crack.resolving)return;crack.errors++;crack.durability=clamp(crack.durability-amount,0,140);alarm=clamp(alarm+3*LOADOUTS[selectedLoadout].alarmMult,0,100);$("durabilityBar").style.width=`${clamp(crack.durability/140*100,0,100)}%`;$("crackMessage").textContent=msg;$("crackMessage").className="crackMessage error";$("safeDoor").classList.remove("shake");void $("safeDoor").offsetWidth;$("safeDoor").classList.add("shake");audio.sfx("error");if(crack.durability<=0)crackFail()}
function crackFail(){if(crack.failed)return;crack.failed=true;crack.safe.lockUntil=performance.now()+4500;alarm=clamp(alarm+9,0,100);banner("ИНСТРУМЕНТ СЛОМАН",1.6);setTimeout(()=>{closeCrack();setHint("Сейф временно заблокирован",true)},650)}
function crackSuccess(){if(crack.resolving||crack.failed)return;crack.resolving=true;crack.progress=1;$("crackProgressBar").style.width="100%";$("crackMessage").textContent="Механизм поддался!";$("crackMessage").className="crackMessage success";audio.sfx("pin");if(crack.stageIndex<crack.stages.length-1){setTimeout(()=>{crack.stageIndex++;crack.resolving=false;renderCrack()},420);return}const elapsed=(performance.now()-crack.started)/1000,meta=SAFE[crack.safe.tier],ideal=crack.errors===0&&elapsed<(crack.safe.tier===4?16:meta.method==="lockpick"?7:9),clean=crack.errors<=1;crack.safe.grade=ideal?"perfect":clean?"clean":"rough";$("safeDoor").classList.add("open");setTimeout(()=>{const s=crack.safe;closeCrack();completeSafe(s)},620)}
function renderCrack(){const mode=crack.stages[crack.stageIndex],meta=SAFE[crack.safe.tier];crack.mode=mode;crack.progress=0;crack.resolving=false;$("crackStageLabel").textContent=`ЭТАП ${crack.stageIndex+1}/${crack.stages.length}`;$("crackProgressBar").style.width="0%";$("durabilityBar").style.width=`${clamp(crack.durability/140*100,0,100)}%`;$("safeDoor").classList.remove("open","shake");$("crackMessage").className="crackMessage";$("crackMessage").textContent="Ошибки создают шум и повышают тревогу.";if(mode==="lockpick")renderLockpick();if(mode==="pins")renderPins();if(mode==="dial")renderDial()}
function renderLockpick(){const kit=LOADOUTS[selectedLoadout],target=rand(-45,45),tol=9+kit.dialBonus+(profile.level>=3?2:0);crack.angle=0;crack.target=target;crack.tolerance=tol;crack.turning=false;$("crackInstruction").textContent="Найди мягкий угол отмычки и удерживай поворот.";$("crackGame").innerHTML=`<div class="lockpickGame"><div class="lockVisual"><div class="sweetHint" id="sweetHint">ИЩИ ПРАВИЛЬНЫЙ УГОЛ</div><div class="pick" id="pick"></div></div><input class="angleRange" id="angleRange" type="range" min="-60" max="60" value="0"><button class="turnButton" id="turnButton" type="button">УДЕРЖИВАТЬ И ПОВОРАЧИВАТЬ</button></div>`;const range=$("angleRange"),btn=$("turnButton"),upd=()=>{crack.angle=Number(range.value);$("pick").style.setProperty("--pick-angle",`${crack.angle}deg`);const d=Math.abs(crack.angle-target),h=$("sweetHint");h.textContent=d<tol?"МЕХАНИЗМ ОСЛАБ":d<tol*2?"ПОЧТИ…":"ИЩИ ПРАВИЛЬНЫЙ УГОЛ";h.style.color=d<tol?"#9cffbd":d<tol*2?"#ffe394":"#a89c8e";if(d<tol*1.35&&Math.floor(performance.now()/180)%2===0)tg?.HapticFeedback?.impactOccurred?.("light")};range.addEventListener("input",upd);upd();btn.addEventListener("pointerdown",e=>{e.preventDefault();crack.turning=true});["pointerup","pointercancel","pointerleave"].forEach(n=>btn.addEventListener(n,()=>crack.turning=false))}
function renderPins(){const count=crack.safe.tier===4?5:4;crack.pins=Array.from({length:count},()=>({target:randInt(1,4),current:0,locked:false}));$("crackInstruction").textContent="Поднимай штифты до светящейся зоны. Перебор сбрасывает штифт.";$("crackGame").innerHTML=`<div class="pinsGame">${crack.pins.map((p,i)=>`<button class="pinColumn" data-pin="${i}" type="button"><i class="pinTarget" style="--target:${13+p.target*20}px"></i><i class="pinStem"></i><i class="pinHead"></i></button>`).join("")}</div>`;$("crackGame").querySelectorAll("[data-pin]").forEach(btn=>btn.addEventListener("click",()=>{const i=Number(btn.dataset.pin),p=crack.pins[i];if(p.locked)return;p.current++;if(p.current===p.target){p.locked=true;btn.classList.add("locked");audio.sfx("pin")}else if(p.current>p.target){p.current=0;crackError(10,"Штифт сорвался — начни его заново.")}const off=-p.current*20;btn.querySelector(".pinStem").style.setProperty("--pin-offset",`${off}px`);btn.querySelector(".pinHead").style.setProperty("--pin-offset",`${off}px`);crack.progress=crack.pins.filter(x=>x.locked).length/count;$("crackProgressBar").style.width=`${crack.progress*100}%`;if(crack.pins.every(x=>x.locked))crackSuccess()}))}
function renderDial(){const kit=LOADOUTS[selectedLoadout];crack.needle=rand(0,360);crack.target=rand(25,335);crack.direction=rng()<.5?-1:1;crack.speed=crack.safe.tier===4?145:115;crack.round=0;crack.rounds=crack.safe.tier===4?4:3;crack.window=34+kit.dialBonus+(profile.level>=4?4:0);crack.tickArmed=true;$("crackInstruction").textContent="Нажимай, когда стрелка входит в широкую зелёную зону.";$("crackGame").innerHTML=`<div class="dialGame"><div class="dialFace"><i class="dialTarget" id="dialTarget"></i><i class="dialNeedle" id="dialNeedle"></i></div><div class="dialInfo"><strong id="dialRound">1/${crack.rounds}</strong><small>Рядом с сектором прозвучит щелчок и лёгкая вибрация.</small><button class="dialTap" id="dialTap" type="button">ЗАФИКСИРОВАТЬ</button></div></div>`;updateDialTarget();$("dialTap").addEventListener("click",dialAttempt)}
function updateDialTarget(){const start=(crack.target-crack.window/2+360)%360;$("dialTarget").style.setProperty("--target-start",`${start}deg`);$("dialTarget").style.setProperty("--target-span",`${crack.window}deg`);$("dialRound").textContent=`${crack.round+1}/${crack.rounds}`}
function dialAttempt(){const d=degDiff(crack.needle,crack.target);if(d<=crack.window/2+4){crack.round++;crack.progress=crack.round/crack.rounds;$("crackProgressBar").style.width=`${crack.progress*100}%`;audio.sfx("pin");if(crack.round>=crack.rounds){crackSuccess();return}crack.target=rand(25,335);crack.direction*=-1;crack.speed*=1.1;crack.tickArmed=true;updateDialTarget();$("crackMessage").textContent="Точное попадание! Следующий сектор быстрее.";$("crackMessage").className="crackMessage success"}else{crackError(9,"Промах — комбинация сбилась.");crack.round=Math.max(0,crack.round-1);crack.progress=crack.round/crack.rounds;$("crackProgressBar").style.width=`${crack.progress*100}%`;crack.target=rand(25,335);updateDialTarget()}}
function updateCrack(dt){if(!crack.active||crack.failed||crack.resolving)return;const kit=LOADOUTS[selectedLoadout];if(crack.mode==="lockpick"&&crack.turning){const d=Math.abs(crack.angle-crack.target);if(d<=crack.tolerance){crack.progress=clamp(crack.progress+dt*.72*kit.hackSpeed,0,1);$("crackProgressBar").style.width=`${crack.progress*100}%`;$("safeDial").style.transform=`translate(-50%,-50%) rotate(${crack.progress*72}deg)`;if(crack.progress>=1)crackSuccess()}else{crack.progress=Math.max(0,crack.progress-dt*.2);crack.durability-=dt*11;$("durabilityBar").style.width=`${clamp(crack.durability/140*100,0,100)}%`;if(crack.durability<=0)crackFail()}}if(crack.mode==="dial"){crack.needle=(crack.needle+crack.direction*crack.speed*dt+360)%360;$("dialNeedle").style.setProperty("--dial-angle",`${crack.needle}deg`);const d=degDiff(crack.needle,crack.target);if(d<crack.window*.8&&crack.tickArmed){crack.tickArmed=false;audio.sfx("pin");tg?.HapticFeedback?.impactOccurred?.("light")}if(d>crack.window*1.5)crack.tickArmed=true}}
function completeSafe(s){if(s.opened)return;s.opened=true;opened++;if(phase==="infiltration")setPhase("heist");const mult=s.grade==="perfect"?1.3:s.grade==="clean"?1.15:1.0,levelBonus=profile.level>=5?1.1:profile.level>=3?1.05:1,reward=Math.round(s.value*mult*levelBonus);loot+=reward;player.bag=clamp(loot/650,0,1);if(s.grade==="perfect"){perfect++;banner("ИДЕАЛЬНЫЙ ВЗЛОМ +30%",1.8);audio.sfx("perfect")}else audio.sfx("safe");alarm=clamp(alarm+(s.tier===4?10:s.tier===3?7:3)*LOADOUTS[selectedLoadout].alarmMult,0,100);burst(s.x,s.y,SAFE[s.tier].color,s.tier===4?45:26);floater(s.x,s.y-18,`+${reward}`,SAFE[s.tier].color);setHint(`${s.grade==="perfect"?"✨":"💰"} ${SAFE[s.tier].label}: +${reward} влияния`,true);advanceTutorial(2);updateMission();if(s.tier===4||opened>=Math.ceil(totalSafes*.7))setPhase("escape")}
function interact(){if(!running||crack.active)return;const secret=nearest(secrets,44,s=>!s.found);if(secret){secret.found=true;secretsGot++;loot+=35;audio.sfx("secret");banner("СЕКРЕТНЫЙ ДОКУМЕНТ +35",1.6);updateMission();return}const term=nearest(terminals,52,t=>!t.used);if(term){term.used=true;if(term.type==="disable"){cameraDisabled=12*LOADOUTS[selectedLoadout].terminalSpeed;alarm=Math.max(0,alarm-16);banner("КАМЕРЫ ОТКЛЮЧЕНЫ",1.8)}else{for(const c of cells)discovered.add(key(c.c,c.r));banner("КАРТА ХРАНИЛИЩА ЗАГРУЖЕНА",1.8)}audio.sfx("emp");return}const vent=nearest(vents,46);if(vent){const pair=vents[vent.pair];if(pair){player.x=pair.x;player.y=pair.y;camera.x=clamp(player.x-viewW/2,0,WORLD_W-viewW);camera.y=clamp(player.y-(viewH-hudSafe)/2,0,WORLD_H-(viewH-hudSafe));banner("ТАЙНЫЙ ПРОХОД",1.2);audio.sfx("smoke")}return}const safe=nearest(safes,54,s=>!s.opened&&performance.now()>s.lockUntil);if(safe){openCrack(safe);return}if(nearExit()){if(loot<=0){setHint("Сначала найди добычу",true);return}finishGame(missionComplete?"Задание выполнено":"Ты ушёл с добычей",missionComplete?1:.82);return}setHint("Подойди к сейфу, терминалу, вентиляции или тайнику",true)}
function useSmoke(){if(!running||crack.active||gadget.smoke<=0)return;gadget.smoke--;smokeTime=5.5;alarm=Math.max(0,alarm-22);for(const c of cameras){c.alert=0;c.state="search"}audio.sfx("smoke");banner("ДЫМ СКРЫВАЕТ ТЕБЯ",1.4);advanceTutorial(2);updateGadgets()}
function useEmp(){if(!running||crack.active||gadget.emp<=0)return;gadget.emp--;cameraDisabled=Math.max(cameraDisabled,9);alarm=Math.max(0,alarm-12);audio.sfx("emp");banner("ЭМИ: КАМЕРЫ И ЛАЗЕРЫ ОТКЛЮЧЕНЫ",1.6);updateGadgets()}
function updateGadgets(){$("gadget1").textContent=`🌫 ДЫМ ×${gadget.smoke}`;$("gadget1").disabled=gadget.smoke<=0;$("gadget2").textContent=`⚡ ИМПУЛЬС ×${gadget.emp}`;$("gadget2").disabled=gadget.emp<=0}
function cameraSees(c){if(smokeTime>0||cameraDisabled>0||player.hidden)return false;const dx=player.x-c.x,dy=player.y-c.y,d=Math.hypot(dx,dy);if(d>c.range)return false;const a=Math.atan2(dy,dx);if(Math.abs(norm(a-c.angle))>c.fov/2)return false;return!segmentBlocked(c.x,c.y,player.x,player.y)}
function updatePlayer(dt){const mag=Math.hypot(moveX,moveY),ox=player.x,oy=player.y;const weight=1-player.bag*.17;if(mag>.04){if(tutorialActive&&tutorialStep===0)advanceTutorial(0);const nx=moveX/mag,ny=moveY/mag,speed=(smokeTime>0?178:158)*weight;player.vx+=(nx*speed-player.vx)*Math.min(1,dt*11);player.vy+=(ny*speed-player.vy)*Math.min(1,dt*11);player.angle=Math.atan2(player.vy,player.vx);idleTime=0}else{player.vx*=Math.pow(.0015,dt);player.vy*=Math.pow(.0015,dt);idleTime+=dt}const dx=player.vx*dt,dy=player.vy*dt;if(!pointInWall(player.x+dx,player.y))player.x+=dx;else{player.vx*=-.15;player.bump=.16;shake=.08}if(!pointInWall(player.x,player.y+dy))player.y+=dy;else{player.vy*=-.15;player.bump=.16;shake=.08}player.stretch+=(clamp(Math.hypot(player.vx,player.vy)/175,0,1)-player.stretch)*Math.min(1,dt*8);player.bump=Math.max(0,player.bump-dt);if(Math.hypot(player.x-ox,player.y-oy)>1&&rng()<dt*17)trails.push({x:player.x-player.vx*.04,y:player.y-player.vy*.04,life:.44,max:.44,size:rand(3,6)});const pc=playerCell();if(pc){reveal(pc.c,pc.r,1);if(pc.zone!==currentZone){currentZone=pc.zone;zoneTimer=1.4;$("zoneBanner").textContent=ZONE[pc.zone].name;$("zoneBanner").classList.add("show")}}player.hidden=!!nearest(covers,26);for(const l of lasers){if(!l.active||cameraDisabled>0)continue;const dx=player.x-l.x,dy=player.y-l.y,along=Math.abs(Math.cos(l.angle)*dx+Math.sin(l.angle)*dy),perp=Math.abs(-Math.sin(l.angle)*dx+Math.cos(l.angle)*dy);if(along<l.length/2&&perp<7){alarm=clamp(alarm+dt*22*LOADOUTS[selectedLoadout].alarmMult,0,100);shake=.12}}
}
function updateSecurity(dt){let det=0,sus=0;for(const c of cameras){c.pause-=dt;if(c.pause<=0){c.angle+=c.speed*dt*(phase==="escape"?1.55:1);if(rng()<dt*.045){c.pause=rand(.25,.8);c.speed*=-1}}const seen=cameraSees(c);c.alert=clamp(c.alert+(seen?dt*1.7:-dt*1.3),0,1);const prev=c.state;c.state=c.alert>.57?"detected":c.alert>.13?"suspicious":"search";if(c.state==="detected")det++;else if(c.state==="suspicious")sus++;if(prev!=="detected"&&c.state==="detected"){banner("КАМЕРА ЗАХВАТИЛА ЦЕЛЬ",1.1);audio.sfx("alarm")}}if(det)alarm+=dt*(17+det*6)*LOADOUTS[selectedLoadout].alarmMult;else if(sus)alarm+=dt*(2.5+sus)*LOADOUTS[selectedLoadout].alarmMult;else alarm-=dt*(player.hidden?12:7);alarm=clamp(alarm,0,100);maxAlarm=Math.max(maxAlarm,alarm);if(alarm>=100)finishGame("Система безопасности тебя поймала",.2)}
function updateRoute(){let target=null,from=playerCell();if(phase==="escape"||timeLeft<=25)target=cellAt(START.c,START.r);else if(idleTime>8){let best=null,d=1e9;for(const s of safes)if(!s.opened){const v=manhattan(from,s);if(v<d){d=v;best=s}}if(best)target=cellAt(best.c,best.r)}route=target?findPath(from,target):[]}
function updateCamera(dt){const h=Math.max(160,viewH-hudSafe),tx=clamp(player.x-viewW*.5,0,Math.max(0,WORLD_W-viewW)),ty=clamp(player.y-h*.57,0,Math.max(0,WORLD_H-h)),e=1-Math.pow(.001,dt);camera.x+=(tx-camera.x)*e;camera.y+=(ty-camera.y)*e}
function updateEffects(dt){particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt});particles=particles.filter(p=>p.life>0);floaters.forEach(f=>{f.life-=dt;f.y-=25*dt});floaters=floaters.filter(f=>f.life>0);trails.forEach(t=>t.life-=dt);trails=trails.filter(t=>t.life>0);shake=Math.max(0,shake-dt);if(zoneTimer>0&&(zoneTimer-=dt)<=0)$("zoneBanner").classList.remove("show");if(bannerTimer>0&&(bannerTimer-=dt)<=0)$("alertBanner").classList.remove("show")}
function update(dt){timeLeft=Math.max(0,duration-(performance.now()-startedAt)/1000);if(smokeTime>0)smokeTime=Math.max(0,smokeTime-dt);if(cameraDisabled>0)cameraDisabled=Math.max(0,cameraDisabled-dt);updatePlayer(dt);updateSecurity(dt);updateCamera(dt);updateEffects(dt);updateRoute();updateMission();const tier=alarm>=85?3:alarm>=60?2:alarm>=30?1:0;stage.classList.toggle("alert-medium",tier===1);stage.classList.toggle("alert-high",tier===2);stage.classList.toggle("alert-critical",tier===3);$("loot").textContent=loot;$("bagBar").style.width=`${player.bag*100}%`;const sec=Math.ceil(timeLeft);$("timer").textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;$("safes").textContent=`СЕЙФЫ ${opened}/${totalSafes}`;$("alarmBar").style.width=`${alarm}%`;$("alarmText").textContent=`${Math.round(alarm)}%`;updateAction();if(timeLeft<=0)finishGame("Время вышло",.35)}
function updateAction(){const b=$("interact");b.className="action main search";const secret=nearest(secrets,44,s=>!s.found),term=nearest(terminals,52,t=>!t.used),vent=nearest(vents,46),safe=nearest(safes,54,s=>!s.opened&&performance.now()>s.lockUntil);if(secret){b.disabled=false;b.className="action main ready";b.textContent="📜 ЗАБРАТЬ ДОКУМЕНТ"}else if(term){b.disabled=false;b.className="action main ready";b.textContent=term.type==="disable"?"💻 ОТКЛЮЧИТЬ КАМЕРЫ":"🗺 СКАЧАТЬ КАРТУ"}else if(vent){b.disabled=false;b.className="action main ready";b.textContent="🌀 В ВЕНТИЛЯЦИЮ"}else if(safe){b.disabled=false;b.className="action main ready";b.textContent=safe.tier===4?"🏛 ВСКРЫТЬ ХРАНИЛИЩЕ":safe.tier===3?"💎 ВЗЛОМАТЬ ЭЛИТНЫЙ СЕЙФ":"🔓 ВСКРЫТЬ СЕЙФ"}else if(nearExit()){b.disabled=false;b.className="action main exit ready";b.textContent=loot?"🚪 УЙТИ С ДОБЫЧЕЙ":"🚪 СНАЧАЛА НАЙДИ ДОБЫЧУ"}else{b.disabled=true;b.textContent="🔎 ИЩИ ЦЕЛЬ"}}
function burst(x,y,color,n=24){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),s=rand(35,130);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.35,.8),max:.8,size:rand(1.5,4),color})}}
function floater(x,y,text,color){floaters.push({x,y,text,color,life:1.2,max:1.2})}
function screen(x,y){return{x:x-camera.x,y:y-camera.y+hudSafe}}
function rounded(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function drawFloor(){const minC=Math.max(0,Math.floor(camera.x/CELL)-1),maxC=Math.min(COLS-1,Math.ceil((camera.x+viewW)/CELL)),minR=Math.max(0,Math.floor(camera.y/CELL)-1),maxR=Math.min(ROWS-1,Math.ceil((camera.y+viewH-hudSafe)/CELL));for(let r=minR;r<=maxR;r++)for(let c=minC;c<=maxC;c++){const cell=cellAt(c,r),m=ZONE[cell.zone],x=c*CELL-camera.x,y=r*CELL-camera.y+hudSafe;ctx.fillStyle=m.floor;ctx.fillRect(x,y,CELL,CELL);ctx.strokeStyle=m.line+"55";ctx.strokeRect(x+.5,y+.5,CELL-1,CELL-1);ctx.fillStyle="#ffffff07";for(let k=16;k<CELL;k+=24)ctx.fillRect(x+k,y,1,CELL)}}
function drawDecor(t){for(const o of decor){const p=screen(o.x,o.y);if(p.x<-40||p.x>viewW+40||p.y<hudSafe-40||p.y>viewH+40)continue;const a=ZONE[o.zone].accent,pulse=.55+.2*Math.sin(t*2+o.pulse);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(o.rot);ctx.globalAlpha=.52;ctx.strokeStyle=a;ctx.fillStyle=a+"24";ctx.lineWidth=1.5;if(o.type==="server"){ctx.fillRect(-17,-25,34,50);for(let y=-18;y<20;y+=10)ctx.strokeRect(-11,y,22,6)}else if(o.type==="cable"||o.type==="coil"){ctx.beginPath();ctx.moveTo(-29,13);ctx.bezierCurveTo(-8,-22,8,24,30,-10);ctx.stroke()}else if(o.type==="vent"){ctx.strokeRect(-16,-12,32,24);for(let x=-11;x<14;x+=6){ctx.beginPath();ctx.moveTo(x,-9);ctx.lineTo(x,9);ctx.stroke()}}else if(o.type==="monitor"||o.type==="cameraRack"){ctx.fillStyle="#071014";ctx.fillRect(-20,-15,40,27);ctx.strokeRect(-20,-15,40,27);ctx.fillStyle=a+"aa";ctx.fillRect(-14,-8,28,3)}else if(o.type==="desk"){ctx.fillRect(-27,-15,54,30);ctx.strokeRect(-27,-15,54,30)}else if(o.type==="laser"||o.type==="emitter"){ctx.shadowBlur=10;ctx.shadowColor=a;ctx.beginPath();ctx.moveTo(-33,0);ctx.lineTo(33,0);ctx.stroke()}else if(o.type==="display"||o.type==="portrait"){ctx.fillRect(-19,-24,38,48);ctx.strokeRect(-19,-24,38,48);ctx.fillStyle="#ffd76c";ctx.beginPath();ctx.arc(0,-5,6,0,Math.PI*2);ctx.fill()}else if(o.type==="goldPile"){ctx.shadowBlur=8;ctx.shadowColor=a;for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(rand(-20,20),rand(-12,13),rand(2,5),0,Math.PI*2);ctx.fill()}}else if(o.type==="crate"){ctx.fillRect(-18,-18,36,36);ctx.strokeRect(-18,-18,36,36);ctx.beginPath();ctx.moveTo(-18,-18);ctx.lineTo(18,18);ctx.moveTo(18,-18);ctx.lineTo(-18,18);ctx.stroke()}else if(o.type==="crack"){ctx.beginPath();ctx.moveTo(-25,-18);ctx.lineTo(-7,-3);ctx.lineTo(-13,14);ctx.lineTo(8,3);ctx.lineTo(24,18);ctx.stroke()}else if(o.type==="rubble"){for(let i=0;i<6;i++)ctx.fillRect(rand(-24,24),rand(-17,17),rand(3,8),rand(2,6))}else if(o.type==="sparks"){ctx.globalAlpha=pulse;ctx.fillStyle=a;for(let i=0;i<5;i++)ctx.fillRect(rand(-20,20),rand(-20,20),2,2)}else{ctx.fillRect(-22,-10,44,20);ctx.strokeRect(-22,-10,44,20)}ctx.restore()}}
function drawWalls(){for(const w of walls){const p=screen(w.x,w.y);if(p.x+w.w<0||p.x>viewW||p.y+w.h<hudSafe||p.y>viewH)continue;const g=ctx.createLinearGradient(p.x,p.y,p.x+w.w,p.y+w.h);g.addColorStop(0,"#4c3b28");g.addColorStop(.5,"#21191a");g.addColorStop(1,"#725631");ctx.fillStyle=g;rounded(ctx,p.x,p.y,w.w,w.h,Math.min(6,w.w/2,w.h/2));ctx.fill();ctx.strokeStyle="#d0a65366";ctx.stroke()}}
function drawSafe(s,t){const p=screen(s.x,s.y),m=SAFE[s.tier],z=m.size;if(p.y<hudSafe-50||p.y>viewH+50)return;ctx.save();ctx.translate(p.x,p.y);const pulse=.75+.25*Math.sin(t*(s.tier+1)+s.id);if(!s.opened){ctx.shadowBlur=s.tier>=3?26*pulse:13*pulse;ctx.shadowColor=m.color}ctx.fillStyle=s.opened?"#151318":s.tier===4?"#805a22":s.tier===3?"#462b60":s.tier===2?"#27454b":"#5b431d";rounded(ctx,-z,-z*.8,z*2,z*1.6,8);ctx.fill();ctx.lineWidth=s.tier===4?4:3;ctx.strokeStyle=s.opened?"#4c4748":m.color;ctx.stroke();ctx.shadowBlur=0;if(!s.opened){ctx.strokeStyle="#ffffff24";ctx.strokeRect(-z+6,-z*.8+6,z*2-12,z*1.6-12);ctx.fillStyle="#09070b";ctx.beginPath();ctx.arc(0,0,s.tier===4?10:7,0,Math.PI*2);ctx.fill();ctx.strokeStyle=m.color;ctx.stroke();for(const [x,y] of [[-z+7,-z*.8+7],[z-7,-z*.8+7],[-z+7,z*.8-7],[z-7,z*.8-7]]){ctx.fillStyle="#d6b978";ctx.beginPath();ctx.arc(x,y,2.4,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function drawCamera(c){const p=screen(c.x,c.y);if(p.y<hudSafe-c.range||p.y>viewH+c.range)return;const color=c.state==="detected"?"#ff365d":c.state==="suspicious"?"#ffc857":"#e34f72";ctx.save();ctx.translate(p.x,p.y);if(smokeTime<=0&&cameraDisabled<=0){ctx.beginPath();ctx.moveTo(0,0);for(let i=0;i<=18;i++){const a=c.angle-c.fov/2+c.fov*i/18,d=rayDistance(c.x,c.y,a,c.range);ctx.lineTo(Math.cos(a)*d,Math.sin(a)*d)}ctx.closePath();const g=ctx.createRadialGradient(0,0,5,0,0,c.range);g.addColorStop(0,color+"55");g.addColorStop(.75,color+"20");g.addColorStop(1,color+"00");ctx.fillStyle=g;ctx.fill()}ctx.globalAlpha=cameraDisabled>0?.3:1;ctx.shadowBlur=c.state==="detected"?20:10;ctx.shadowColor=color;ctx.fillStyle=c.state==="detected"?"#d92f50":"#79283d";ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=c.state==="suspicious"?"#ffe28b":"#ff9bad";ctx.lineWidth=2.3;ctx.beginPath();ctx.ellipse(0,0,10.5,6.2,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(0,0,3.2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawObjects(t){for(const c of covers){const p=screen(c.x,c.y);ctx.fillStyle="#0a080dcc";ctx.strokeStyle=ZONE[cellAt(c.c,c.r).zone].accent+"55";rounded(ctx,p.x-21,p.y-18,42,36,8);ctx.fill();ctx.stroke()}for(const term of terminals){const p=screen(term.x,term.y);ctx.save();ctx.shadowBlur=term.used?0:14;ctx.shadowColor="#70d9e8";ctx.fillStyle=term.used?"#181719":"#10262b";rounded(ctx,p.x-20,p.y-16,40,32,7);ctx.fill();ctx.strokeStyle=term.used?"#555":"#70d9e8";ctx.stroke();ctx.fillStyle="#70d9e8";ctx.fillRect(p.x-12,p.y-8,24,4);ctx.restore()}for(const v of vents){const p=screen(v.x,v.y);ctx.strokeStyle="#a995d6";ctx.strokeRect(p.x-17,p.y-13,34,26);for(let x=-12;x<14;x+=6){ctx.beginPath();ctx.moveTo(p.x+x,p.y-10);ctx.lineTo(p.x+x,p.y+10);ctx.stroke()}}for(const s of secrets)if(!s.found&&Math.hypot(player.x-s.x,player.y-s.y)<90){const p=screen(s.x,s.y);ctx.save();ctx.globalAlpha=.55+.35*Math.sin(t*4);ctx.fillStyle="#ffe394";ctx.font="18px system-ui";ctx.textAlign="center";ctx.fillText("📜",p.x,p.y);ctx.restore()}for(const l of lasers){const p=screen(l.x,l.y);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(l.angle);ctx.globalAlpha=cameraDisabled>0?.15:.55+.25*Math.sin(t*3+l.phase);ctx.strokeStyle="#ff365d";ctx.shadowBlur=12;ctx.shadowColor="#ff365d";ctx.beginPath();ctx.moveTo(-l.length/2,0);ctx.lineTo(l.length/2,0);ctx.stroke();ctx.restore()}}
function drawExit(t){const p=screen(exit.x,exit.y),pulse=.6+.4*Math.sin(t*3);ctx.save();ctx.shadowBlur=18+10*pulse;ctx.shadowColor="#63f5a1";ctx.fillStyle="#123d29";rounded(ctx,p.x,p.y,exit.w,exit.h,11);ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#63f5a1";ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#b8ffd0";ctx.font="900 10px system-ui";ctx.textAlign="center";ctx.fillText("ВЫХОД",p.x+exit.w/2,p.y+36);ctx.restore()}
function drawRoute(){if(route.length<2)return;ctx.save();ctx.strokeStyle=phase==="escape"||timeLeft<25?"#63f5a0aa":"#ffd76c88";ctx.lineWidth=4;ctx.setLineDash([8,9]);ctx.beginPath();route.forEach((p,i)=>{const s=screen(p.x,p.y);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y)});ctx.stroke();ctx.restore()}
function drawPlayer(t){const p=screen(player.x,player.y);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(player.angle);const sx=(1+player.stretch*.22)*(player.bump? .84:1),sy=(1-player.stretch*.12)*(player.bump?1.15:1);ctx.scale(sx,sy);ctx.shadowBlur=player.hidden?10:22;ctx.shadowColor=alarm>60?"#ff365d":"#a76bff";const g=ctx.createRadialGradient(-3,-4,2,0,0,player.r*1.5);g.addColorStop(0,"#d6a6ff");g.addColorStop(.45,"#a76bff");g.addColorStop(1,"#5e2aa0");ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,player.r+player.bag*2,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(p.x,p.y-player.r-9);ctx.rotate(Math.sin(t*5)*.08+player.vx*.0008);ctx.font="19px system-ui";ctx.textAlign="center";ctx.fillText("👑",0,3);ctx.restore();if(player.hidden){ctx.strokeStyle="#70d9e877";ctx.setLineDash([5,4]);ctx.beginPath();ctx.arc(p.x,p.y,25,0,Math.PI*2);ctx.stroke()}}
function drawEffects(){for(const t of trails){const p=screen(t.x,t.y);ctx.globalAlpha=t.life/t.max*.34;ctx.fillStyle="#a76bff";ctx.beginPath();ctx.arc(p.x,p.y,t.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const p0 of particles){const p=screen(p0.x,p0.y);ctx.globalAlpha=p0.life/p0.max;ctx.fillStyle=p0.color;ctx.fillRect(p.x,p.y,p0.size,p0.size)}ctx.globalAlpha=1;for(const f of floaters){const p=screen(f.x,f.y);ctx.globalAlpha=f.life/f.max;ctx.fillStyle=f.color;ctx.font="900 13px system-ui";ctx.textAlign="center";ctx.fillText(f.text,p.x,p.y)}ctx.globalAlpha=1}
function drawMini(){const w=Math.max(1,miniCanvas.clientWidth),h=Math.max(1,miniCanvas.clientHeight);mini.setTransform(dpr,0,0,dpr,0,0);mini.clearRect(0,0,w,h);mini.fillStyle="#050408";mini.fillRect(0,0,w,h);const pad=6,sx=(w-pad*2)/WORLD_W,sy=(h-pad*2)/WORLD_H;for(const c of cells){if(!discovered.has(key(c.c,c.r)))continue;mini.fillStyle=ZONE[c.zone].floor;mini.fillRect(pad+c.c*CELL*sx,pad+c.r*CELL*sy,CELL*sx+.5,CELL*sy+.5)}mini.strokeStyle="#d2aa5b99";for(const w0 of walls){const wc=clamp(Math.floor((w0.x+2)/CELL),0,COLS-1),wr=clamp(Math.floor((w0.y+2)/CELL),0,ROWS-1);if(!discovered.has(key(wc,wr)))continue;mini.strokeRect(pad+w0.x*sx,pad+w0.y*sy,Math.max(1,w0.w*sx),Math.max(1,w0.h*sy));}mini.fillStyle="#63f5a1";mini.fillRect(pad+exit.x*sx,pad+exit.y*sy,4,4);for(const s of safes)if(!s.opened&&discovered.has(key(s.c,s.r))){mini.fillStyle=SAFE[s.tier].color;const r=s.tier===4?4:s.tier===3?3:2;mini.fillRect(pad+s.x*sx-r,pad+s.y*sy-r,r*2,r*2)}for(const c of cameras)if(discovered.has(key(c.c,c.r))){mini.fillStyle=c.state==="detected"?"#ff365d":"#d95a78";mini.beginPath();mini.arc(pad+c.x*sx,pad+c.y*sy,1.7,0,Math.PI*2);mini.fill()}for(const t of terminals)if(!t.used&&discovered.has(key(t.c,t.r))){mini.fillStyle="#70d9e8";mini.fillRect(pad+t.x*sx-2,pad+t.y*sy-2,4,4)}const x=pad+player.x*sx,y=pad+player.y*sy;mini.save();mini.translate(x,y);mini.rotate(player.angle+Math.PI/2);mini.fillStyle="#f3c4ff";mini.beginPath();mini.moveTo(0,-5);mini.lineTo(4,4);mini.lineTo(0,2);mini.lineTo(-4,4);mini.closePath();mini.fill();mini.restore()}
let ticker=0;function draw(now=0){ticker=now/1000;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,viewW,viewH);const bg=ctx.createLinearGradient(0,0,0,viewH);bg.addColorStop(0,"#1d1417");bg.addColorStop(1,"#07060b");ctx.fillStyle=bg;ctx.fillRect(0,0,viewW,viewH);ctx.save();ctx.beginPath();ctx.rect(0,hudSafe,viewW,viewH-hudSafe);ctx.clip();if(shake)ctx.translate(rand(-4,4)*shake,rand(-4,4)*shake);drawFloor();drawDecor(ticker);drawRoute();drawExit(ticker);drawObjects(ticker);for(const s of safes)drawSafe(s,ticker);for(const c of cameras)drawCamera(c);drawWalls();drawEffects();drawPlayer(ticker);ctx.restore();drawMini()}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);viewW=Math.max(1,r.width);viewH=Math.max(1,r.height);hudSafe=parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--hud-safe"))||124;canvas.width=Math.round(viewW*dpr);canvas.height=Math.round(viewH*dpr);miniCanvas.width=Math.round(Math.max(1,miniCanvas.clientWidth)*dpr);miniCanvas.height=Math.round(Math.max(1,miniCanvas.clientHeight)*dpr)}addEventListener("resize",resize);
function loop(now){if(!running)return;const dt=Math.min(.034,(now-lastFrame)/1000||.016);lastFrame=now;if(crack.active)updateCrack(dt);else update(dt);draw(now);if(running)requestAnimationFrame(loop)}
async function finishGame(reason,keep){if(ended)return;ended=true;running=false;if(crack.active)closeCrack();secured=Math.round(loot*keep);const grade=missionComplete&&maxAlarm<35?"S":missionComplete?"A":secured>300?"B":"C";$("runGrade").textContent=grade;$("resultTitle").textContent=reason;$("collected").textContent=loot;$("secured").textContent=secured;$("opened").textContent=`${opened}/${totalSafes}`;$("perfectHacks").textContent=perfect;$("secretsFound").textContent=`${secretsGot}/${secrets.length}`;$("maxAlarm").textContent=`${Math.round(maxAlarm)}%`;$("finish").classList.remove("hidden");const xp=Math.round(40+secured*.12+perfect*18+secretsGot*20+(missionComplete?50:0));profile.xp+=xp;profile.runs++;profile.best=Math.max(profile.best,secured);while(profile.xp>=100+profile.level*65)profile.level++;saveProfile();$("xpReward").textContent=`Опыт медвежатника: +${xp} XP · Уровень ${profile.level}`;if(demo||!sessionId)$("reward").textContent="Демонстрационный режим: влияние не начисляется в баланс.";else try{const r=await api("finish",{session_id:sessionId,score:secured,stats:{collected:loot,secured,opened,total_safes:totalSafes,max_alarm:Math.round(maxAlarm),escaped:keep>.8,map_code:mapCode,mission:mission.id,mission_complete:missionComplete,perfect_hacks:perfect,secrets:secretsGot,grade}});$("reward").innerHTML=`🏆 Получено влияния: <b>+${r.actual_reward}</b><br>Баланс: <b>${r.balance}</b><br><small>${r.message}</small>`}catch(e){$("reward").innerHTML=`<span class="error">${e.message}</span>`}}
const joy=$("joystick"),knob=$("knob");let joyId=null;function setJoy(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy),max=r.width*.31,k=Math.min(1,max/(len||1)),x=dx*k,y=dy*k;knob.style.transform=`translate(${x}px,${y}px)`;moveX=x/max;moveY=y/max;joy.classList.add("active")}joy.addEventListener("pointerdown",e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);setJoy(e)});joy.addEventListener("pointermove",e=>{if(e.pointerId===joyId)setJoy(e)});function clearJoy(e){if(joyId!==null&&(e.pointerId===undefined||e.pointerId===joyId)){joyId=null;moveX=moveY=0;knob.style.transform="";joy.classList.remove("active")}}joy.addEventListener("pointerup",clearJoy);joy.addEventListener("pointercancel",clearJoy);
$("interact").addEventListener("click",interact);$("gadget1").addEventListener("click",useSmoke);$("gadget2").addEventListener("click",useEmp);$("start").addEventListener("click",startGame);$("again").addEventListener("click",()=>{$("finish").classList.add("hidden");$("intro").classList.remove("hidden");pickMission();updateProfileCard()});$("crackAbort").addEventListener("click",abortCrack);$("minimapWrap").addEventListener("click",()=>$("minimapWrap").classList.toggle("expanded"));$("soundToggle").addEventListener("click",()=>{audio.unlock();audio.toggle()});$("tutorialSkip").addEventListener("click",abortTutorial);$("loadouts").addEventListener("click",e=>{const b=e.target.closest("[data-loadout]");if(!b)return;selectedLoadout=b.dataset.loadout;document.querySelectorAll(".loadout").forEach(x=>x.classList.toggle("selected",x===b));audio.sfx("click")});const goGames=()=>location.href=`/games/?${params.toString()}`;$("back").addEventListener("click",goGames);$("toGames").addEventListener("click",goGames);$("introToGames").addEventListener("click",goGames);
resize();rng=seeded(Date.now());pickMission();updateProfileCard();buildMaze();buildObjects();draw();audio.apply();
})();
