(()=>{
  "use strict";
  (window.__heistV90Patches||(window.__heistV90Patches=[])).push((source,replaceFunction)=>{
    source=replaceFunction(source,"renderLockpick","renderPins",`  function setupTimingPins(kind,master){
    const reinforced=kind==="pins";
    crack.mode=kind;crack.pinCount=master?5:reinforced?4:3;crack.pinIndex=0;crack.pinPos=rand(.08,.24);crack.pinDir=1;crack.pinSpeed=master?1.45:reinforced?1.28:1.05;crack.pinTarget=rand(.28,.72);crack.pinBase=crack.pinTarget;crack.pinTolerance=master?.075:reinforced?.105:.135;crack.pinPhase=rand(0,6);crack.pinMovingZone=reinforced;crack.progress=0;
    $("crackInstruction").textContent=reinforced?"Штифт и зелёная зона двигаются. Нажми, когда индикатор окажется внутри зоны.":"Штифт двигается сам. Нажми, когда индикатор войдёт в зелёную зону.";
    $("crackGame").innerHTML='<div class="v90PinGame '+(reinforced?'reinforced':'mechanical')+'"><div class="v90PinHead"><b id="v90PinLabel">ШТИФТ 1/'+crack.pinCount+'</b><span>Ошибка сбрасывает только текущий штифт</span></div><div class="v90PinSteps" id="v90PinSteps">'+Array.from({length:crack.pinCount},(_,i)=>'<i class="'+(i===0?'active':'')+'">'+(i+1)+'</i>').join("")+'</div><div class="v90PinMeter"><i class="v90PinZone" id="v90PinZone"></i><i class="v90PinNeedle" id="v90PinNeedle"></i></div><button class="v90FixPin" id="v90FixPin" type="button">ЗАФИКСИРОВАТЬ ШТИФТ</button></div>';
    const zone=$("v90PinZone");zone.style.left=(crack.pinTarget-crack.pinTolerance)*100+"%";zone.style.width=crack.pinTolerance*200+"%";
    $("v90FixPin").addEventListener("click",()=>{
      if(crack.resolving)return;const diff=Math.abs(crack.pinPos-crack.pinTarget),ok=diff<=crack.pinTolerance;
      if(ok){const steps=$("v90PinSteps").children;steps[crack.pinIndex]?.classList.remove("active");steps[crack.pinIndex]?.classList.add("done");crack.pinIndex++;crack.progress=crack.pinIndex/crack.pinCount;$("crackProgressBar").style.width=crack.progress*100+"%";tg?.HapticFeedback?.impactOccurred?.("medium");if(crack.pinIndex>=crack.pinCount){crackStageSuccess();return;}steps[crack.pinIndex]?.classList.add("active");$("v90PinLabel").textContent="ШТИФТ "+(crack.pinIndex+1)+"/"+crack.pinCount;crack.pinSpeed=Math.min(1.85,crack.pinSpeed+.09);crack.pinPos=crack.pinDir>0?.08:.92;crack.pinTarget=rand(.26,.74);crack.pinBase=crack.pinTarget;crack.pinPhase=rand(0,6);zone.style.left=(crack.pinTarget-crack.pinTolerance)*100+"%";$("crackMessage").textContent="Щелчок! Следующий штифт.";$("crackMessage").className="crackMessage success";}
      else{const early=crack.pinPos<crack.pinTarget;crackError(master?10:reinforced?8:6,early?"СЛИШКОМ РАНО — дождись зелёной зоны.":"СЛИШКОМ ПОЗДНО — нажми чуть раньше.");crack.pinPos=crack.pinDir>0?.08:.92;}
    });
  }
  function renderLockpick(master){setupTimingPins("lockpick",master);}`);

    source=replaceFunction(source,"renderPins","renderCircuit",`  function renderPins(master){setupTimingPins("pins",master);}`);

    source=replaceFunction(source,"renderDial","updateDialTarget",`  function renderDial(master){
    crack.mode="dial";crack.needle=rand(0,360);crack.target=rand(55,305);crack.direction=rng()<.5?-1:1;crack.round=0;crack.rounds=3;crack.window=master?48:58;crack.speed=master?142:116;crack.dialNear=false;crack.progress=0;
    $("crackInstruction").textContent="Стрелка вращается сама. Нажми, когда она войдёт в зелёную зону.";
    $("crackGame").innerHTML='<div class="v90DialGame"><div class="v90DialWheel"><i class="v90DialTicks"></i><i class="v90DialZone" id="dialTarget"></i><i class="v90DialNeedle" id="dialNeedle"></i><span class="v90DialHub"></span></div><div class="v90DialInfo"><strong id="dialRound">СЕКТОР 1/3</strong><b id="dialDirection"></b><small>Стрелка вращается автоматически. Нажимай только в зелёном секторе.</small><button class="v90DialTap" id="dialTap" type="button">ЗАФИКСИРОВАТЬ</button></div></div>';
    updateDialTarget();$("dialTap").addEventListener("click",dialAttempt);
  }`);

    source=replaceFunction(source,"updateDialTarget","dialAttempt",`  function updateDialTarget(){
    const zone=$("dialTarget"),needle=$("dialNeedle"),round=$("dialRound"),dir=$("dialDirection");if(zone){zone.style.setProperty("--target-angle",crack.target+"deg");zone.style.setProperty("--target-size",crack.window+"deg");}if(needle)needle.style.setProperty("--dial-angle",crack.needle+"deg");if(round)round.textContent="СЕКТОР "+(crack.round+1)+"/"+crack.rounds;if(dir)dir.textContent=crack.direction>0?"↻ СТРЕЛКА ПО ЧАСОВОЙ":"↺ СТРЕЛКА ПРОТИВ ЧАСОВОЙ";
  }`);

    source=replaceFunction(source,"dialAttempt","updateCrack",`  function dialAttempt(){
    if(crack.mode!=="dial"||crack.resolving)return;const diff=degDiff(crack.needle,crack.target),inside=diff<=crack.window/2+5;
    if(inside){crack.round++;crack.progress=crack.round/crack.rounds;$("crackProgressBar").style.width=crack.progress*100+"%";tg?.HapticFeedback?.impactOccurred?.("heavy");if(crack.round>=crack.rounds){crackStageSuccess();return;}crack.target=rand(55,305);crack.direction*=-1;crack.speed=Math.min(176,crack.speed+14);crack.dialNear=false;updateDialTarget();$("crackMessage").textContent="Точное попадание! Следующий сектор.";$("crackMessage").className="crackMessage success";}
    else{const signed=((crack.needle-crack.target+540)%360)-180;crackError(crack.safe.tier===4?9:6,(signed<0?"СЛИШКОМ РАНО":"СЛИШКОМ ПОЗДНО")+" · промах "+Math.round(diff)+"°");crack.target=rand(55,305);crack.dialNear=false;updateDialTarget();}
  }`);

    source=replaceFunction(source,"updateCrack","completeSafe",`  function updateCrack(dt){
    if(!crack.active||crack.failed||crack.resolving)return;if(crack.errorCooldown>0)crack.errorCooldown-=dt;crack.noise=clamp(crack.noise+dt*(crack.safe.tier===4?1.05:.58),0,110);updateNoiseUI();if(crack.noise>=100)raiseNoiseAlarm();
    if(crack.mode==="lockpick"||crack.mode==="pins"){
      crack.pinPos+=crack.pinDir*dt*crack.pinSpeed;if(crack.pinPos>=.98||crack.pinPos<=.02){crack.pinPos=clamp(crack.pinPos,.02,.98);crack.pinDir*=-1;}if(crack.pinMovingZone){crack.pinTarget=clamp(crack.pinBase+Math.sin(performance.now()/780+crack.pinPhase)*.11,.18,.82);const zone=$("v90PinZone");if(zone)zone.style.left=(crack.pinTarget-crack.pinTolerance)*100+"%";}const needle=$("v90PinNeedle");if(needle)needle.style.left=crack.pinPos*100+"%";const good=Math.abs(crack.pinPos-crack.pinTarget)<=crack.pinTolerance;$("v90FixPin")?.classList.toggle("ready",good);
    }
    if(crack.mode==="dial"){
      crack.needle=(crack.needle+crack.direction*crack.speed*dt+360)%360;const needle=$("dialNeedle");if(needle)needle.style.setProperty("--dial-angle",crack.needle+"deg");const near=degDiff(crack.needle,crack.target)<=crack.window/2+5;$("dialTap")?.classList.toggle("ready",near);if(near&&!crack.dialNear){crack.dialNear=true;tg?.HapticFeedback?.impactOccurred?.("light");}if(!near)crack.dialNear=false;
    }
  }`);

    source=replaceFunction(source,"drawFloor","drawDecor",`  function drawFloor(){
    const visibleH=viewH-hudSafe,minC=Math.max(0,Math.floor(camera.x/CELL)-1),maxC=Math.min(COLS-1,Math.ceil((camera.x+viewW)/CELL)),minR=Math.max(0,Math.floor(camera.y/CELL)-1),maxR=Math.min(ROWS-1,Math.ceil((camera.y+visibleH)/CELL));
    for(let r=minR;r<=maxR;r++)for(let c=minC;c<=maxC;c++){const cell=cellAt(c,r),meta=ZONE_META[cell.zone],x=c*CELL-camera.x,y=r*CELL-camera.y+hudSafe;const g=ctx.createLinearGradient(x,y,x+CELL,y+CELL);g.addColorStop(0,meta.floor);g.addColorStop(.55,"#0d0b12");g.addColorStop(1,meta.line+"22");ctx.fillStyle=g;ctx.fillRect(x,y,CELL,CELL);ctx.strokeStyle="#d5a94a20";ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,CELL-1,CELL-1);ctx.strokeStyle=meta.line+"28";ctx.beginPath();ctx.moveTo(x+8,y+CELL*.72);ctx.bezierCurveTo(x+CELL*.28,y+CELL*.42,x+CELL*.64,y+CELL*.9,x+CELL-8,y+CELL*.24);ctx.stroke();if((c*7+r*11)%5===0){ctx.fillStyle="#ffffff05";ctx.fillRect(x+12,y+14,CELL-24,1);ctx.fillRect(x+18,y+CELL-18,CELL-36,1);}}
  }`);

    source=replaceFunction(source,"drawWalls","drawSafe",`  function drawWalls(){
    const depth=7;for(const w of walls){const p=screen(w.x,w.y);if(p.x+w.w<0||p.x>viewW||p.y+w.h<hudSafe||p.y>viewH)continue;ctx.save();ctx.shadowColor="#000";ctx.shadowBlur=14;ctx.shadowOffsetY=8;const face=ctx.createLinearGradient(p.x,p.y,p.x+w.w,p.y+w.h);face.addColorStop(0,"#5b4630");face.addColorStop(.32,"#231b1e");face.addColorStop(.72,"#151117");face.addColorStop(1,"#6d512f");ctx.fillStyle=face;rounded(ctx,p.x,p.y,w.w,w.h,Math.min(6,w.w/2,w.h/2));ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+w.w,p.y);ctx.lineTo(p.x+w.w+depth,p.y-depth);ctx.lineTo(p.x+depth,p.y-depth);ctx.closePath();const top=ctx.createLinearGradient(p.x,p.y-depth,p.x,p.y+3);top.addColorStop(0,"#b98a45");top.addColorStop(.45,"#6d4d2c");top.addColorStop(1,"#2a2020");ctx.fillStyle=top;ctx.fill();ctx.beginPath();ctx.moveTo(p.x+w.w,p.y);ctx.lineTo(p.x+w.w,p.y+w.h);ctx.lineTo(p.x+w.w+depth,p.y+w.h-depth);ctx.lineTo(p.x+w.w+depth,p.y-depth);ctx.closePath();ctx.fillStyle="#171117";ctx.fill();ctx.strokeStyle="#d6ad62aa";ctx.lineWidth=1.5;rounded(ctx,p.x,p.y,w.w,w.h,Math.min(6,w.w/2,w.h/2));ctx.stroke();ctx.strokeStyle="#fff3c32b";ctx.beginPath();ctx.moveTo(p.x+3,p.y+2);ctx.lineTo(p.x+w.w-3,p.y+2);ctx.stroke();ctx.restore();}
  }`);

    source=replaceFunction(source,"drawSafe","drawCamera",`  function drawSafe(safe,t){
    const p=screen(safe.x,safe.y),meta=SAFE_META[safe.tier],s=meta.size;if(p.x<-80||p.x>viewW+80||p.y<hudSafe-80||p.y>viewH+80)return;ctx.save();ctx.globalAlpha=.55;ctx.fillStyle="#000";ctx.beginPath();ctx.ellipse(p.x,p.y+s*.95,s*1.05,s*.34,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(p.x,p.y);const pulse=.76+.24*Math.sin(t*2.6+safe.id);ctx.shadowBlur=safe.opened?0:safe.tier>=3?36*pulse:20*pulse;ctx.shadowColor=meta.color;ctx.fillStyle=safe.opened?"#17151a":"#241d22";rounded(ctx,-s-5,-s*.86-5,(s+5)*2,(s*.86+5)*2,10);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=safe.opened?"#50484a":meta.color;ctx.lineWidth=safe.tier===4?4:3;ctx.stroke();if(safe.tier===1){const g=ctx.createLinearGradient(-s,-s,s,s);g.addColorStop(0,"#8b672d");g.addColorStop(.5,"#2a211b");g.addColorStop(1,"#c19645");ctx.fillStyle=g;rounded(ctx,-s,-s*.76,s*2,s*1.52,8);ctx.fill();ctx.strokeStyle="#f0cd7b";ctx.stroke();ctx.fillStyle="#0b090d";ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#e5bd63";ctx.stroke();ctx.fillStyle="#c9a24f";ctx.fillRect(s*.55,-9,6,24);}else if(safe.tier===2){const g=ctx.createLinearGradient(-s,-s,s,s);g.addColorStop(0,"#15444c");g.addColorStop(.5,"#10242a");g.addColorStop(1,"#6bd6e4");ctx.fillStyle=g;rounded(ctx,-s,-s*.76,s*2,s*1.52,8);ctx.fill();ctx.strokeStyle="#75e5ef";ctx.stroke();ctx.fillStyle="#071014";rounded(ctx,-s*.45,-s*.35,s*.9,s*.5,4);ctx.fill();ctx.fillStyle="#6be6f1";ctx.font="900 7px system-ui";ctx.textAlign="center";ctx.fillText("ACCESS",0,-2);for(let iy=0;iy<3;iy++)for(let ix=0;ix<3;ix++){ctx.fillStyle="#b6f7ff";ctx.fillRect(-8+ix*7,5+iy*6,3,3);}}else if(safe.tier===3){ctx.fillStyle="#3c2450";rounded(ctx,-s,-s*.76,s*2,s*1.52,8);ctx.fill();ctx.strokeStyle="#d984ff";ctx.stroke();ctx.save();ctx.rotate(t*.25);ctx.strokeStyle="#f0b9ff88";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.stroke();ctx.restore();for(let i=0;i<5;i++){const a=t*.8+i*Math.PI*2/5;ctx.fillStyle="#e4a7ff";ctx.globalAlpha=.35+.3*Math.sin(t*3+i);ctx.beginPath();ctx.arc(Math.cos(a)*(s+9),Math.sin(a)*(s*.55+7),2,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}else{ctx.fillStyle="#5d431e";rounded(ctx,-s,-s*.8,s*2,s*1.6,9);ctx.fill();ctx.strokeStyle="#ffd76c";ctx.stroke();ctx.fillStyle="#141014";ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#ffd76c";ctx.lineWidth=3;ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(Math.cos(a)*5,Math.sin(a)*5);ctx.lineTo(Math.cos(a)*13,Math.sin(a)*13);ctx.stroke();}ctx.fillStyle="#ffe6a5";ctx.font="900 9px system-ui";ctx.textAlign="center";ctx.fillText("VAULT",0,-s*.9);}if(safe.opened){ctx.fillStyle="#050507cc";ctx.fillRect(-s+5,-s*.65,s*1.6,s*1.3);}ctx.restore();
  }`);

    source=replaceFunction(source,"drawCamera","drawRoute",`  function drawCamera(cam){
    const p=screen(cam.x,cam.y);if(p.x<-cam.range||p.x>viewW+cam.range||p.y<hudSafe-cam.range||p.y>viewH+cam.range)return;const color=cam.state==="detected"?"#ff304f":cam.state==="suspicious"?"#ffc45e":"#da4668";ctx.save();ctx.translate(p.x,p.y);if(smokeTime<=0){ctx.beginPath();ctx.moveTo(0,0);const samples=22;for(let i=0;i<=samples;i++){const a=cam.angle-cam.fov/2+cam.fov*i/samples,d=rayDistance(cam.x,cam.y,a,cam.range);ctx.lineTo(Math.cos(a)*d,Math.sin(a)*d);}ctx.closePath();const g=ctx.createRadialGradient(0,0,4,0,0,cam.range);g.addColorStop(0,color+"88");g.addColorStop(.62,color+"42");g.addColorStop(1,color+"00");ctx.fillStyle=g;ctx.fill();}ctx.rotate(cam.angle+Math.PI/2);const variant=cam.id%3;ctx.shadowBlur=cam.state==="detected"?28:16;ctx.shadowColor=color;if(variant===0){ctx.fillStyle="#17161d";rounded(ctx,-10,-13,20,26,6);ctx.fill();ctx.strokeStyle="#8d263c";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#282733";ctx.beginPath();ctx.arc(0,-15,7,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-4,-17,8,3);ctx.fillStyle="#09090c";ctx.fillRect(-13,3,6,15);ctx.fillRect(7,3,6,15);}else if(variant===1){ctx.fillStyle="#17131c";ctx.beginPath();ctx.arc(0,0,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,4,0,Math.PI*2);ctx.fill();for(let i=0;i<4;i++){ctx.save();ctx.rotate(i*Math.PI/2);ctx.fillStyle="#272230";ctx.fillRect(-3,13,6,9);ctx.restore();}}else{ctx.fillStyle="#6f243d";rounded(ctx,-14,-8,28,16,8);ctx.fill();ctx.strokeStyle="#ffb0c1";ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(0,0,9,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#200911";ctx.beginPath();ctx.arc(0,0,3,0,Math.PI*2);ctx.fill();}ctx.restore();
  }`);

    return source;
  });
})();
