(()=>{
  "use strict";
  (window.__heistV88Patches||(window.__heistV88Patches=[])).push((source,replaceFunction)=>{
    source=replaceFunction(source,"dialAttempt","updateCrack","  function dialAttempt(){\n    if(crack.mode!==\"dial\"||crack.resolving)return;const diff=degDiff(crack.needle,crack.target),enough=crack.travel>=70,inside=diff<=crack.window/2+6;if(enough&&inside){crack.round++;crack.progress=crack.round/crack.rounds;$(\"crackProgressBar\").style.width=crack.progress*100+\"%\";tg?.HapticFeedback?.impactOccurred?.(\"heavy\");if(crack.round>=crack.rounds){crackStageSuccess();return;}crack.target=rand(55,305);crack.direction*=-1;crack.travel=0;crack.wrongTurn=0;updateDialTarget();$(\"crackMessage\").textContent=\"Щелчок! Смени направление и набери следующий оборот.\";$(\"crackMessage\").className=\"crackMessage success\";}else{crackError(crack.safe.tier===4?10:7,!enough?\"Слишком короткий поворот — прокрути диск хотя бы на четверть оборота.\":\"Промах на \"+Math.round(diff)+\"° — отпускай диск внутри зелёной зоны.\");crack.travel=0;crack.wrongTurn=0;crack.target=rand(55,305);updateDialTarget();}\n  }");
    source=replaceFunction(source,"updateCrack","completeSafe","  function updateCrack(dt){\n    if(!crack.active||crack.failed||crack.resolving)return;if(crack.errorCooldown>0)crack.errorCooldown-=dt;crack.noise=clamp(crack.noise+dt*(crack.safe.tier===4?1.35:.72),0,110);updateNoiseUI();if(crack.noise>=100)raiseNoiseAlarm();\n    if(crack.mode===\"lockpick\"){if(!crack.tensionLocked){crack.tension+=crack.tensionDir*dt*(crack.safe.tier===4?.82:1.02);if(crack.tension>=1||crack.tension<=0){crack.tension=clamp(crack.tension,0,1);crack.tensionDir*=-1;}const n=$(\"tensionNeedle\");if(n)n.style.left=crack.tension*100+\"%\";}else{crack.stability+=crack.stabilityDir*dt*(crack.safe.tier===4?1.75:1.45);if(crack.stability>=1||crack.stability<=0){crack.stability=clamp(crack.stability,0,1);crack.stabilityDir*=-1;}const n=$(\"stabilityNeedle\");if(n)n.style.left=crack.stability*100+\"%\";$(\"stabilityBox\")?.classList.toggle(\"good\",Math.abs(crack.stability-.5)<(crack.safe.tier===4?.12:.16));}}\n    if(crack.mode===\"pins\"){const now=performance.now()/1000;crack.pins.forEach((pin,i)=>{if(pin.locked)return;pin.target=clamp(pin.base+Math.sin(now*pin.speed+pin.phase)*.12,.16,.84);const el=$(\"crackGame\")?.querySelector('[data-pin=\"'+i+'\"] .pinTarget');if(el)el.style.setProperty(\"--pin-target\",pin.target);});}\n  }");
    source=replaceFunction(source,"completeSafe","interact","  function completeSafe(safe){\n    if(safe.opened)return;safe.opened=true;opened++;const jackpot=rng()<(safe.tier===4?.34:safe.tier===3?.22:.16)?Math.round(safe.value*(safe.tier===4?.75:.55)):0,mult=safe.hackMult||1,reward=Math.round((safe.value+jackpot)*mult);loot+=reward;alarm=clamp(alarm+(safe.tier===4?10:safe.tier===3?7:3),0,100);burst(safe.x,safe.y,safe.tier>=3?\"#d985ff\":\"#ffd76c\",safe.tier===4?58:34,safe.tier===4?200:150);addFloater(safe.x,safe.y-20,\"+\"+reward,safe.tier>=3?\"#edc2ff\":\"#ffe59a\",1.35);flyLoot(safe,reward);if(safe.tier>=3){fxLayer.insertAdjacentHTML(\"beforeend\",'<i class=\"screenFlash\"></i>');setTimeout(()=>fxLayer.querySelector(\".screenFlash\")?.remove(),500);escapeMode=true;stage.classList.add(\"escape-mode\");const remain=Math.min(timeLeft,safe.tier===4?48:60);startedAt=performance.now()-(duration-remain)*1000;showBanner(safe.tier===4?\"ХРАНИЛИЩЕ ОТКРЫТО — БЕГИ К ВЫХОДУ\":\"ЭЛИТНЫЙ СЕЙФ ВСКРЫТ — НАЧАЛСЯ ПОБЕГ\",2.3);}const grade=safe.hackGrade||\"ВЗЛОМ ЗАВЕРШЁН\";setHint((jackpot?\"🍀 \":\"\")+grade+\": +\"+reward+\" влияния\",true);tg?.HapticFeedback?.notificationOccurred?.(\"success\");idleTime=0;updateRoute();\n  }");
    source=replaceFunction(source,"updatePlayer","updateCameras","  function updatePlayer(dt){\n    const input=Math.hypot(moveX,moveY),oldX=player.x,oldY=player.y;if(input>.04){const nx=moveX/input,ny=moveY/input,base=smokeTime>0?180:158,bagPenalty=Math.min(34,loot*.035),speed=Math.max(118,base-bagPenalty);player.vx+=(nx*speed-player.vx)*Math.min(1,dt*11);player.vy+=(ny*speed-player.vy)*Math.min(1,dt*11);player.angle=Math.atan2(player.vy,player.vx);idleTime=0;}else{player.vx*=Math.pow(.0015,dt);player.vy*=Math.pow(.0015,dt);idleTime+=dt;}const dx=player.vx*dt,dy=player.vy*dt;if(!pointInWall(player.x+dx,player.y)){player.x+=dx;}else{player.vx*=-.15;player.bump=.18;shake=Math.max(shake,.1);}if(!pointInWall(player.x,player.y+dy)){player.y+=dy;}else{player.vy*=-.15;player.bump=.18;shake=Math.max(shake,.1);}const speed=Math.hypot(player.vx,player.vy);player.stretch+=(clamp(speed/175,0,1)-player.stretch)*Math.min(1,dt*8);player.bump=Math.max(0,player.bump-dt);if(Math.hypot(player.x-oldX,player.y-oldY)>1&&rng()<dt*18)trails.push({x:player.x-player.vx*.045,y:player.y-player.vy*.045,life:.48,max:.48,size:rand(3.5,7)});const cell=playerCell();if(cell){revealAround(cell.c,cell.r,1);if(cell.zone!==currentZone){currentZone=cell.zone;zoneTimer=1.35;$(\"zoneBanner\").textContent=ZONE_META[cell.zone].label;$(\"zoneBanner\").classList.add(\"show\");}}\n  }");
    return source;
  });
})();
