(()=>{
  'use strict';
  const tg=window.Telegram?.WebApp;
  tg?.ready();tg?.expand();tg?.setHeaderColor?.('#090713');tg?.setBackgroundColor?.('#090713');
  const initData=tg?.initData||'';
  const params=new URLSearchParams(location.search);
  let selectedChat=Number(params.get('chat_id')||localStorage.getItem('adminChat')||0);
  let selectedUser=Number(params.get('user_id')||localStorage.getItem('adminUser')||0);
  let state=null,activeTab='home',toastTimer=null,formConfirm=null,searchTimer=null;
  const $=id=>document.getElementById(id);
  const fmt=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const headers={'X-Telegram-Init-Data':initData,'Content-Type':'application/json'};
  const STATUS_NAMES={active:'идёт бой',resolving:'подсчёт наград',victory:'победа',cancelled:'отменён',defeat:'поражение',expired:'время истекло'};
  const ACTION_NAMES={points_delta:'Изменение влияния',points_set:'Точное влияние',role_set:'Изменение роли',mute:'Мут участника',unmute:'Снятие мута',cooldown_user_chat:'Сброс личных КД',cooldown_user_global:'Сброс глобальных КД',stats_user_reset:'Сброс статистики участника',tree_delta:'Изменение очков древа',tree_set:'Точные очки древа',tree_refund:'Возврат очков древа',knowledge_week_reset:'Сброс недельного лимита',chat_cooldowns_reset:'Сброс КД беседы',chat_stats_reset:'Сброс статистики беседы',chat_profiles_recalculate:'Пересчёт профилей',database_check:'Проверка базы',boss_start:'Запуск рейда',boss_hp_delta:'Изменение HP босса',boss_hp_set:'Точное HP босса',boss_pressure_reset:'Сброс давления',boss_pressure_fill:'Заполнение давления',boss_cooldowns_reset:'Сброс КД рейда',boss_phase_set:'Смена фазы',boss_attack_set:'Выбор атаки',boss_attack_now:'Атака босса',boss_refresh_post:'Обновление поста',boss_recover:'Восстановление рейда',boss_victory:'Победа в рейде',boss_cancel:'Отмена рейда',undo:'Отмена изменения'};

  function toast(text,type=''){const node=$('toast');node.textContent=text;node.className=`toast show ${type}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.className='toast',2800)}
  function loading(show){$('loading').classList.toggle('hidden',!show)}
  async function request(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{...headers,...(options.headers||{})}});const data=await response.json().catch(()=>({ok:false,reason:'Сервер вернул непонятный ответ.'}));if(!response.ok||!data.ok)throw new Error(data.reason||'Действие не выполнено.');return data}
  async function loadState(silent=false){if(!silent)loading(true);$('connectionState').textContent='Обновление…';try{state=await request(`/admin-app/api/state?chat_id=${selectedChat||0}&user_id=${selectedUser||0}`);selectedChat=Number(state.selected_chat?.chat_id)||0;selectedUser=Number(state.target?.user_id)||0;localStorage.setItem('adminChat',selectedChat);localStorage.setItem('adminUser',selectedUser);render();$('connectionState').textContent='● Подключено';$('connectionState').style.color='#67e2aa'}catch(e){$('connectionState').textContent='● Ошибка соединения';$('connectionState').style.color='#ff6f83';toast(e.message,'error')}finally{loading(false)}}
  async function act(action,extra={}){try{tg?.HapticFeedback?.impactOccurred?.('light');const result=await request('/admin-app/api/action',{method:'POST',body:JSON.stringify({action,chat_id:selectedChat,user_id:selectedUser,...extra})});toast(result.message||'Готово');tg?.HapticFeedback?.notificationOccurred?.('success');await loadState(true)}catch(e){toast(e.message,'error');tg?.HapticFeedback?.notificationOccurred?.('error')}}

  function metric(icon,label,value,note=''){return `<article class="metric"><span>${icon}</span><small>${esc(label)}</small><b>${esc(value)}</b>${note?`<em>${esc(note)}</em>`:''}</article>`}
  function render(){
    $('versionText').textContent=state.version||'Reality 64';
    $('chatSelect').innerHTML=(state.chats||[]).map(c=>`<option value="${c.chat_id}" ${Number(c.chat_id)===selectedChat?'selected':''}>${esc(c.title)} · ${c.users}</option>`).join('')||'<option>Нет бесед</option>';
    const t=state.target;
    $('targetAvatar').textContent=t?.role?.emoji||'?';$('targetName').textContent=t?.full_name||'Не выбран';
    $('targetMeta').textContent=t?`${t.role.emoji} ${t.role.title} · ${fmt(t.points)} влияния · ID ${t.user_id}`:'—';
    $('pointsSubtitle').textContent=`Текущий баланс: ${fmt(t?.points||0)}`;
    renderHome();renderUsers(state.quick_users||[],'quickUsers');renderKnowledge();renderRaid();renderHistory();
  }
  function renderHome(){const boss=state.boss;const health=state.health||{};$('homeMetrics').innerHTML=[metric('🤖','Версия',state.version||'—','бот работает'),metric('👥','Участников',String(state.selected_chat?state.chats.find(c=>Number(c.chat_id)===selectedChat)?.users||0:0),'в выбранной беседе'),metric('🌌','Рейд',boss?(STATUS_NAMES[String(boss.status)]||boss.status):'не запускался',boss?`${fmt(boss.hp)} / ${fmt(boss.max_hp)} HP`:'можно запустить'),metric('🩺','База данных',health.status||'—',health.status==='ok'?'ошибок не найдено':'нужна проверка')].join('')}
  function userMarkup(u){const selected=Number(u.user_id)===selectedUser;return `<button class="user-item ${selected?'selected':''}" data-user-id="${u.user_id}"><span class="user-avatar">${u.role?.emoji||'👤'}</span><span><b>${esc(u.full_name)}</b><small>${u.username?'@'+esc(u.username):'ID '+u.user_id} · ${esc(u.role?.title||'')}</small></span><strong>${fmt(u.points)}</strong></button>`}
  function renderUsers(users,id){$(id).innerHTML=users.length?users.map(userMarkup).join(''):'<div class="empty">Участники не найдены.</div>'}
  async function searchUsers(){const q=$('userSearch').value.trim();try{const data=await request(`/admin-app/api/users?chat_id=${selectedChat}&q=${encodeURIComponent(q)}`);renderUsers(data.users||[],'searchResults')}catch(e){toast(e.message,'error')}}

  function renderKnowledge(){const k=state.knowledge||{weekly_tree_points:0,profile:{total:0,spent:0,available:0},levels:[],buffs:{}};$('knowledgeMetrics').innerHTML=[metric('🌳','Всего очков',fmt(k.profile.total),`доступно ${fmt(k.profile.available)}`),metric('✨','Потрачено',fmt(k.profile.spent),`${k.levels.length} активных талантов`),metric('📅','За неделю',`${fmt(k.weekly_tree_points)} / 12`,'рейдовые очки · лимит 12')].join('');$('talentList').innerHTML=k.levels.length?k.levels.map(x=>`<div class="talent-item"><span><b>${esc(x.name)}</b><small>${esc(x.branch)}</small></span><strong>${x.level}/${x.max}</strong></div>`).join(''):'<div class="empty">Участник ещё не прокачивал таланты.</div>';const labels={boss_damage:'Урон по боссу',boss_crit_chance:'Шанс крита',boss_crit_power:'Сила крита',first_hit_x3:'Первый удар ×3',influence:'Бонус влияния',activity:'Награды активности',tasks:'Награды заданий',daily_double:'Ежедневное удвоение',penalty_reduction:'Снижение штрафов',avoid_penalty:'Шанс избежать штрафа',sabotage_reduction:'Защита от саботажа',weekly_armor:'Недельная броня',game_reward:'Награды игр',rare_reward:'Редкая награда',second_chance:'Второй шанс',daily_reroll:'Ежедневный реролл'};const buffs=Object.entries(k.buffs||{}).filter(([,v])=>Number(v)>0);$('buffList').innerHTML=buffs.length?buffs.map(([key,val])=>`<div class="buff-item"><span>${esc(labels[key]||key)}</span><strong>${Number(val)<=1?Math.round(Number(val)*100)+'%':esc(val)}</strong></div>`).join(''):'<div class="empty">Активных баффов пока нет.</div>'}

  function renderRaid(){const b=state.boss;if(!b){$('raidContent').innerHTML=`<article class="boss-card"><div class="boss-sigil">🌌</div><h3>Центр Вселенной не вызван</h3><p>Запусти новый рейд для выбранной беседы.</p><button class="wide-button" data-action="boss_start">🌌 Запустить босса</button></article>`;return}const status=STATUS_NAMES[String(b.status)]||String(b.status);const canStart=!['active','resolving'].includes(String(b.status));const hp=Math.max(0,Math.min(100,b.hp/Math.max(1,b.max_hp)*100));const pressure=Math.max(0,Math.min(100,b.pressure/Math.max(1,b.pressure_max)*100));$('raidContent').innerHTML=`
    <article class="boss-card"><div class="boss-sigil">👁</div><h3>ЦЕНТР ВСЕЛЕННОЙ</h3><p>${esc(status)} · фаза ${b.phase}/4 · ${b.fighters} участников</p><div class="hp-track"><i style="width:${hp}%"></i></div><div class="boss-numbers"><b>${fmt(b.hp)} HP</b><span>${fmt(b.max_hp)} HP</span></div><div class="pressure-track"><i style="width:${pressure}%"></i></div><div class="boss-numbers"><b>⚡ ${fmt(b.pressure)}/${fmt(b.pressure_max)}</b><span>${Math.round(pressure)}%</span></div><div class="boss-detail-grid"><div class="boss-detail"><small>Следующая атака</small><b>${esc(b.planned_action_icon)} ${esc(b.planned_action_name)}</b></div><div class="boss-detail"><small>В строю</small><b>${b.alive}/${b.fighters}</b></div></div>${b.player_url?`<button class="wide-button" data-open-player="${esc(b.player_url)}">🎮 Открыть как игрок</button>`:''}${canStart?'<button class="wide-button positive" data-action="boss_start">🌌 Запустить новый рейд</button>':''}</article>
    <article class="panel raid-controls"><div class="panel-title"><span>❤️</span><div><b>Здоровье босса</b><small>Быстрые и точные изменения</small></div></div><div class="step-grid"><button data-action="boss_hp_delta" data-value="-5000">−5000</button><button data-action="boss_hp_delta" data-value="-1000">−1000</button><button data-action="boss_hp_delta" data-value="1000">+1000</button><button data-action="boss_hp_delta" data-value="5000">+5000</button></div><button class="wide-button" data-form="bossHp">✍️ Установить точное HP</button><div class="subheading">ПРИНУДИТЕЛЬНАЯ ФАЗА</div><div class="action-grid two"><button data-phase="1">I · Раскол</button><button data-phase="2">II · Тревога</button><button data-phase="3">III · Ярость</button><button data-phase="4">IV · Натиск</button></div></article>
    <article class="panel"><div class="panel-title"><span>⚡</span><div><b>Давление и кулдауны</b><small>Инструменты тестирования боя</small></div></div><div class="action-grid two"><button data-action="boss_pressure_reset">Сбросить давление</button><button data-action="boss_pressure_fill">Заполнить давление</button><button class="full" data-action="boss_cooldowns_reset">⏱ Сбросить КД участников</button></div></article>
    <article class="panel"><div class="panel-title"><span>🗯</span><div><b>Следующая атака</b><small>Назначь и запусти вручную</small></div></div><div class="attack-select"><select id="attackSelect"><option value="shield">🪞 Все мне завидуют</option><option value="silence">🗯 Тебя никто не слушает</option><option value="single">🌌 Сокрушить самооценку</option><option value="mass">👥 Вы всего лишь массовка</option></select><button class="raid-button" id="setAttackButton">Назначить</button></div><button class="wide-button" data-action="boss_attack_now">💥 Атаковать сейчас</button></article>
    <article class="panel"><div class="panel-title"><span>🛠</span><div><b>Обслуживание рейда</b><small>Сообщение, восстановление и завершение</small></div></div><div class="action-grid two"><button data-action="boss_refresh_post">🔄 Обновить пост</button><button data-action="boss_recover">🧯 Восстановить зависший</button><button class="danger-soft" data-confirm-action="boss_cancel" data-confirm-title="Отменить рейд?" data-confirm-text="Бой завершится без наград.">🛑 Отменить</button><button class="danger-soft" data-confirm-action="boss_victory" data-confirm-title="Завершить победой?" data-confirm-text="Босс получит 0 HP, а всем активным участникам будут выданы реальные награды.">🏆 Победа и награды</button></div></article>
    <article class="panel"><div class="panel-title"><span>📜</span><div><b>Последние события</b><small>Журнал текущего боя</small></div></div><div class="log-list">${(b.logs||[]).map(x=>`<div class="log-entry">${esc(x)}</div>`).join('')||'<div class="empty">Событий пока нет.</div>'}</div></article>`}

  function renderHistory(){const items=state.history||[];$('historyList').innerHTML=items.length?items.map(x=>`<article class="history-item ${x.undone?'undone':''}"><header><b>${esc(ACTION_NAMES[x.action]||x.action)}</b><time>${new Date(x.created_at*1000).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></header><p>${esc(x.detail)}</p><footer><span>чат ${x.chat_id||'—'}</span><span>цель ${x.target_user_id||'—'}</span>${x.reversible&&!x.undone?'<span>можно отменить</span>':''}${x.undone?'<span>отменено</span>':''}</footer></article>`).join(''):'<div class="empty">История действий пока пуста.</div>'}

  function switchTab(tab){activeTab=tab;document.querySelectorAll('[data-screen]').forEach(x=>x.classList.toggle('active',x.dataset.screen===tab));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'})}
  function closeModal(){$('modal').classList.remove('open');$('modal').setAttribute('aria-hidden','true');formConfirm=null}
  function openModal({icon='⚙',title,text='',field='',confirm='Подтвердить',onConfirm}){$('modalIcon').textContent=icon;$('modalTitle').textContent=title;$('modalText').textContent=text;$('modalField').innerHTML=field;$('modalConfirm').textContent=confirm;formConfirm=onConfirm;$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false');setTimeout(()=>$('modalField').querySelector('input,select')?.focus(),100)}
  function openNumberForm(kind){const map={points:['⭐','Установить влияние','Новое количество очков',state.target?.points||0,'points_set'],tree:['🌳','Установить очки древа','Общее количество очков',state.knowledge?.profile?.total||0,'tree_set'],bossHp:['❤️','Установить HP босса','Значение от 0 до максимального HP',state.boss?.hp||0,'boss_hp_set']};const config=map[kind];if(!config)return;const [icon,title,text,current,action]=config;openModal({icon,title,text,field:`<input id="modalNumber" type="number" value="${current}">`,onConfirm:()=>{const value=Number($('modalNumber').value);closeModal();act(action,{value})}})}
  function confirmAction(button){openModal({icon:'⚠️',title:button.dataset.confirmTitle||'Подтвердить действие',text:button.dataset.confirmText||'Это действие может изменить данные.',confirm:'Да, выполнить',onConfirm:()=>{closeModal();act(button.dataset.confirmAction)}})}

  document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab],[data-tab-open]');if(tab){switchTab(tab.dataset.tab||tab.dataset.tabOpen);return}const user=e.target.closest('[data-user-id]');if(user){selectedUser=Number(user.dataset.userId);localStorage.setItem('adminUser',selectedUser);loadState(true);return}const role=e.target.closest('[data-role]');if(role){act('role_set',{role:role.dataset.role});return}const mute=e.target.closest('[data-mute]');if(mute){act('mute',{minutes:Number(mute.dataset.mute)});return}const phase=e.target.closest('[data-phase]');if(phase){act('boss_phase_set',{phase:Number(phase.dataset.phase)});return}const form=e.target.closest('[data-form]');if(form){openNumberForm(form.dataset.form);return}const confirm=e.target.closest('[data-confirm-action]');if(confirm){confirmAction(confirm);return}const action=e.target.closest('[data-action]');if(action){act(action.dataset.action,{value:Number(action.dataset.value||0)});return}const open=e.target.closest('[data-open-player]');if(open){tg?.openLink?.(open.dataset.openPlayer,{try_instant_view:false});return}if(e.target.closest('[data-modal-close]'))closeModal()});
  $('modalConfirm').addEventListener('click',()=>formConfirm?.());$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});
  $('selectSelfButton').addEventListener('click',()=>{selectedUser=Number(state?.admin?.user_id)||0;localStorage.setItem('adminUser',selectedUser);loadState(true)});
  $('chatSelect').addEventListener('change',()=>{selectedChat=Number($('chatSelect').value);selectedUser=0;loadState()});$('refreshButton').addEventListener('click',()=>loadState());$('searchButton').addEventListener('click',searchUsers);$('userSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchUsers,280)});
  document.addEventListener('click',e=>{if(e.target.id==='setAttackButton'){act('boss_attack_set',{attack:$('attackSelect').value})}});
  window.addEventListener('online',()=>loadState(true));window.addEventListener('offline',()=>toast('Нет соединения с интернетом.','error'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadState(true)});tg?.BackButton?.onClick?.(()=>{if($('modal').classList.contains('open'))closeModal();else if(activeTab!=='home')switchTab('home');else tg.close()});
  loadState();
})();
