y{const ac=new(window.AudioContext||window.webkitAudioContext)(),master=ac.createGain();master.gain.value=.12;master.connect(ac.destination);audio={ac,master}}catch(_){}}
function tone(f=120,d=.08,type='square',vol=.12){if(!audio)return;const o=audio.ac.createOscillator(),g=audio.ac.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.ac.currentTime+d);o.connect(g).connect(audio.master);o.start();o.stop(audio.ac.currentTime+d)}
function resize(){const r=canvas.getBoundingClientRect();vw=Math.max(1,r.width);vh=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);light.width=canvas.width;light.height=canvas.height;ctx.setTransform(dpr,0,0,dpr,0,0);lctx.setTransform(dpr,0,0,dpr,0,0)}
function inside(r,x,y,p=0){return x>=r.x-p&&x<=r.x+r.w+p&&y>=r.y-p&&y<=r.y+r.h+p}function walkable(x,y){return rooms.some(r=>inside(r,x,y))||corridors.some(r=>inside(r,x,y))}
function doorClosed(i){if(state.activeRoom>=0&&(i===state.activeRoom||i===state.activeRoom-1))return true;return i>=state.unlockedThrough}
function blocked(x,y,p=0){return doors.some((d,i)=>doorClosed(i)&&inside(d,x,y,p))}
function canMove(x,y,r=12){const pts=[[0,0],[r,0],[-r,0],[0,r],[0,-r],[r*.7,r*.7],[-r*.7,r*.7],[r*.7,-r*.7],[-r*.7,-r*.7]];return pts.every(([dx,dy])=>walkable(x+dx,y+dy)&&!blocked(x+dx,y+dy,1))}
function roomAt(x,y){return rooms.findIndex(r=>inside(r,x,y))}
function setCaption(t,s=2){$('caption').textContent=t;state.messageUntil=performance.now()+s*1000}
function banner(room,b='ЗАЧИСТКА НАЧАТА'){const el=$('waveBanner');el.querySelector('small').textContent='СЕКТОР '+(room+1);el.querySelector('b').textContent=b;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function spawnPoint(room){const r=rooms[room],side=Math.floor(rand()*4),m=28;let x,y;if(side===0){x=r.x+m+rand()*(r.w-m*2);y=r.y+m}else if(side===1){x=r.x+r.w-m;y=r.y+m+rand()*(r.h-m*2)}else if(side===2){x=r.x+m+rand()*(r.w-m*2);y=r.y+r.h-m}else{x=r.x+m;y=r.y+m+rand()*(r.h-m*2)}if(dist(x,y,player.x,player.y)<150)return spawnPoint(room);return{x,y}}
function spawnEnemy(type){const d=enemyDefs[type],p=spawnPoint(state.activeRoom);state.enemies.push({type,x:p.x,y:p.y,hp:d.hp,maxHp:d.hp,r:d.r,speed:d.speed,damage:d.damage,score:d.score,color:d.color,attackAt:0,shootAt:0,chargeAt:0,hit:0});if(type==='boss'){$('bossHud').classList.remove('hidden');banner(5,'ТЯЖЁЛЫЙ ОХОТНИК')}}
function startRoom(i){if(i<0||i>=rooms.length||i<=state.roomsCleared-1)return;state.activeRoom=i;state.spawnQueue=[...waveTypes[i]];state.nextSpawn=performance.now()+400;banner(i);setCaption(i===5?'Главная камера открыта. Уничтожь Тяжёлого охотника!':'Двери заблокированы. Уничтожь всех заражённых.',3)}
function nearestEnemy(){let best=null,bd=Infinity;for(const e of state.enemies){const d=dist(player.x,player.y,e.x,e.y);if(d<bd&&d<500){bd=d;best=e}}return best}
function shoot(now){if(player.reloading||now-player.lastShot<player.fireDelay)return;if(player.mag<=0){reload();return}const target=nearestEnemy();let ax=player.facingX,ay=player.facingY;if(target){const d=dist(player.x,player.y,target.x,target.y)||1;ax=(target.x-player.x)/d;ay=(target.y-player.y)/d;player.facingX=ax;player.facingY=ay}player.lastShot=now;player.mag--;state.shots++;state.bullets.push({x:player.x+ax*23,y:player.y+ay*23,vx:ax*620,vy:ay*620,life:.85,damage:player.damage,pierce:player.pierce});state.flash=.16;state.shake=Math.max(state.shake,2.4);tone(150,.055,'square',.18);vibrate('light');if(player.mag===0&&player.reserve>0)setTimeout(reload,120)}
function reload(){if(player.reloading||player.mag>=player.magSize||player.reserve<=0||!state.running)return;player.reloading=true;player.reloadEnd=performance.now()+1150;$('reloadText').classList.remove(