'hidden');tone(230,.06,'square',.07)}
function finishReload(){const need=player.magSize-player.mag,take=Math.min(need,player.reserve);player.mag+=take;player.reserve-=take;player.reloading=false;$('reloadText').classList.add('hidden');tone(510,.07,'square',.1)}
function throwGrenade(){if(player.grenades<=0||state.paused||state.finished)return;player.grenades--;const t=nearestEnemy(),dx=t?t.x-player.x:player.facingX*220,dy=t?t.y-player.y:player.facingY*220,d=Math.hypot(dx,dy)||1;state.grenadeObjs.push({x:player.x,y:player.y,vx:dx/d*250,vy:dy/d*250,time:.62});$('grenades').textContent=player.grenades;tone(280,.08,'square',.12)}
function explode(g){state.shake=13;state.flash=.7;tone(48,.35,'sawtooth',.28);vibrate('heavy');particles(g.x,g.y,45,'#ffb54f');for(const e of [...state.enemies]){const d=dist(g.x,g.y,e.x,e.y);if(d<125)damageEnemy(e,105*(1-d/170))}}
function damageEnemy(e,amount){e.hp-=amount;e.hit=.12;state.hits++;particles(e.x,e.y,5,'#ff526b');if(e.hp<=0)killEnemy(e)}
function killEnemy(e){const i=state.enemies.indexOf(e);if(i<0)return;state.enemies.splice(i,1);state.kills++;state.score+=e.score;if(player.vamp)player.hp=Math.min(player.maxHp,player.hp+player.vamp);particles(e.x,e.y,e.type==='boss'?55:18,e.type==='boss'?'#ffcf62':'#ff435f');if(e.type==='boss')$('bossHud').classList.add('hidden');const roll=rand();if(roll<.24)state.pickups.push({type:'ammo',x:e.x,y:e.y,r:10});else if(roll<.32)state.pickups.push({type:'med',x:e.x,y:e.y,r:10});tone(e.type==='boss'?70:95,.12,'sawtooth',.1)}
function damagePlayer(amount){const now=performance.now();if(now<player.invuln)return;player.invuln=now+650;player.hp=Math.max(0,player.hp-amount);state.shake=10;$('damageFx').classList.add('show');setTimeout(()=>$('damageFx').classList.remove('show'),180);vibrate('heavy');tone(55,.22,'sawtooth',.22);if(player.hp<=0)finish(false,'Заражённые прорвали оборону.')}
function input(){let x=joy.x,y=joy.y;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++;const m=Math.hypot(x,y);return m>1?{x:x/m,y:y/m,m:1}:{x,y,m}}
function movePlayer(dt){const i=input();if(i.m<.05)return;player.facingX=i.x/i.m;player.facingY=i.y/i.m;const s=player.speed,dx=i.x*s*dt,dy=i.y*s*dt;if(canMove(player.x+dx,player.y,player.r))player.x+=dx;if(canMove(player.x,player.y+dy,player.r))player.y+=dy}
function updateEnemies(dt,now){for(const e of [...state.enemies]){e.hit=Math.max(0,e.hit-dt);let dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(e.type==='spitter'&&d>135&&d<390){if(now>e.shootAt){e.shootAt=now+1500;state.enemyBullets.push({x:e.x,y:e.y,vx:dx/d*230,vy:dy/d*230,life:2.2,damage:9});tone(85,.09,'sine',.08)}if(d<185){dx=-dx;dy=-dy}}else if(e.type==='boss'&&now>e.chargeAt&&d>100){e.chargeAt=now+3000;e.chargeUntil=now+550}const mult=e.chargeUntil>now?2.9:1;e.x+=dx/d*e.speed*mult*dt;e.y+=dy/d*e.speed*mult*dt;const r=rooms[state.activeRoom];e.x=clamp(e.x,r.x+e.r,r.x+r.w-e.r);e.y=clamp(e.y,r.y+e.r,r.y+r.h-e.r);if(d<e.r+player.r+5&&now>e.attackAt){e.attackAt=now+700;damagePlayer(e.damage)}}
for(let a=0;a<state.enemies.length;a++)for(let b=a+1;b<state.enemies.length;b++){const A=state.enemies[a],B=state.enemies[b],dx=B.x-A.x,dy=B.y-A.y,d=Math.hypot(dx,dy)||1,min=A.r+B.r+3;if(d<min){const p=(min-d)/2;A.x-=dx/d*p;A.y-=dy/d*p;B.x+=dx/d*p;B.y+=dy/d*p}}}
function updateProjectiles(dt){for(const b of [...state.bullets]){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let remove=b.life<=0||!walkable(b.x,b.y);if(!remove)for(const e of [...state.enemies])if(dist(b.x,b.y,e.x,e.y)<e.r+4){damageEnemy(e,b.damage);if(b.pierce>0)b.pierce--;else{remove=true;break}}if(remove)state.bullets.splice(state.bullets.indexOf(b),1)}for(const b of [...state.enemyBullets]){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(dist(b.x,b.y,player.x,player.