(() => {
  const tg = window.Telegram?.WebApp;
  tg?.ready(); tg?.expand(); tg?.setHeaderColor?.('#050407'); tg?.setBackgroundColor?.('#050407');
  const $ = id => document.getElementById(id);
  const initData = tg?.initData || '';
  const params = new URLSearchParams(location.search);
  let bossId = tg?.initDataUnsafe?.start_param || params.get('boss') || '';
  let state = null, busy = false, tickTimer, pollTimer;
  const headers = {'Content-Type':'application/json','X-Telegram-Init-Data':initData};
  const colors = ['#d7a43f','#8b48a5','#367aa3','#3a9a51'];
  const fmt = n => new Intl.NumberFormat('ru-RU').format(Math.max(0,Number(n)||0));
  const duration = sec => { sec=Math.max(0,Math.ceil(sec||0)); const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60; return h ? `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}` : `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}` };
  function toast(text){ const el=$('toast'); el.textContent=text; el.classList.add('show'); clearTimeout(el.t); el.t=setTimeout(()=>el.classList.remove('show'),2400); tg?.HapticFeedback?.notificationOccurred?.('warning'); }
  async function api(path, options={}){ const res=await fetch(`/boss-app/api/boss/${path}`,{...options,headers:{...headers,...options.headers}}); const data=await res.json().catch(()=>({reason:'Ошибка ответа сервера'})); if(!res.ok||!data.ok) throw new Error(data.reason||'Не удалось выполнить действие'); return data; }
  async function start(){ try{ state=await api('session',{method:'POST',body:JSON.stringify({boss_id:bossId})}); bossId=state.battle.boss_id; render(); pollTimer=setInterval(refresh,4000); tickTimer=setInterval(tick,250); }catch(e){ $('bossHpText').textContent=e.message; toast(e.message); demo(); } }
  async function refresh(){ if(busy||!bossId)return; try{state=await api(`state?boss_id=${encodeURIComponent(bossId)}`);render();}catch(e){} }
  function render(){ if(!state)return; const b=state.battle, me=state.self||{}; const pct=Math.max(0,Math.min(100,b.hp/b.max_hp*100)); $('bossHpFill').style.width=`${pct}%`; $('bossHpText').textContent=`${fmt(b.hp)} / ${fmt(b.max_hp)} HP`; $('bossPercent').textContent=`${Math.round(pct)}%`; $('phaseText').textContent=`${b.phase}/4`; $('bossImage').src=`/boss-app/assets/boss_phase_${Math.min(4,Math.max(1,b.phase))}.webp`; $('score').textContent=fmt(me.damage||0); $('abilityName').textContent=me.ability_name||'Способность роли'; $('abilityHint').textContent=me.ability_hint||'Особая атака вашей роли'; const list=[...(state.fighters||[])].sort((a,b)=>b.damage-a.damage).slice(0,4); while(list.length<4)list.push(null); $('fighters').innerHTML=list.map((f,i)=>f?`<article class="fighter ${f.is_self?'self':''}" style="--card:${colors[i]}"><div class="avatar">${(f.name||'?').trim()[0]}</div><b>${esc(f.name)}</b><small>${esc(f.role_title)}</small><em>${fmt(f.hp)}/${fmt(f.max_hp)}</em><div class="mini-hp"><i style="width:${Math.max(0,f.hp/f.max_hp*100)}%"></i></div></article>`:`<article class="fighter empty-fighter" style="--card:${colors[i]}"><div class="avatar">?</div><b>Свободно</b><small>Ждём героя</small><em>—</em><div class="mini-hp"></div></article>`).join(''); $('logs').innerHTML=(state.logs?.length?state.logs:['Бой только начался.']).map(x=>`<div>• ${esc(x)}</div>`).join(''); tick(); }
  function tick(){ if(!state)return; const now=Date.now()/1000, offset=now-(state.now||now), serverNow=(state.now||now)+offset, b=state.battle, cd=state.self?.cooldowns||{}; $('battleTimer').textContent=duration(b.ends_at-serverNow); $('nextAction').textContent=duration(b.next_action_at-serverNow); setCd('attack',cd.attack,'attackCooldown',serverNow); setTextCd(cd.heal,'healCooldown',serverNow); setTextCd(cd.defend,'defendCooldown',serverNow); setTextCd(cd.ability,'abilityCooldown',serverNow); }
  function remaining(base,serverNow){ return Math.max(0,(base||0)-(serverNow-(state.now||serverNow))); }
  function setTextCd(base,id,now){ const r=remaining(base,now); $(id).textContent=r?duration(r):'готово'; const btn=$(id).closest('button'); if(btn)btn.disabled=busy||r>0; }
  function setCd(name,base,id,now){ const r=remaining(base,now), total=Math.max(5,base||5); $(id).style.width=`${Math.min(100,r/total*100)}%`; const btn=$(id).closest('button'); if(btn)btn.disabled=busy||r>0; $('attackHint').textContent=r?`снова через ${duration(r)}`:'нанести сокрушительный удар'; }
  async function action(type,button){ if(busy||!state)return; busy=true; document.querySelectorAll('[data-action]').forEach(b=>b.disabled=true); button.classList.add('firing'); tg?.HapticFeedback?.impactOccurred?.(type==='hit'?'heavy':'medium'); try{ const result=await api('action',{method:'POST',body:JSON.stringify({boss_id:bossId,action:type})}); toast(result.message||result.log_text||successText(type,result)); state=await api(`state?boss_id=${encodeURIComponent(bossId)}`); render(); }catch(e){toast(e.message)}finally{busy=false;button.classList.remove('firing');render();} }
  const successText=(t,r)=>t==='heal'?`Восстановлено ${fmt(r.healed)} HP`:t==='defend'?'Защита активирована':`Нанесено ${fmt(r.damage)} урона`;
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function openModal(title='МАГАЗИН',text='В РАЗРАБОТКЕ'){ $('modalTitle').textContent=title;$('modalText').textContent=text;$('modal').classList.add('show');$('modal').setAttribute('aria-hidden','false');tg?.HapticFeedback?.impactOccurred?.('light'); }
  function demo(){ if(initData||bossId)return; state={ok:true,now:Math.floor(Date.now()/1000),battle:{boss_id:'demo',hp:32480000,max_hp:50000000,phase:2,ends_at:Date.now()/1000+7620,next_action_at:Date.now()/1000+3},self:{name:'Илья',role_title:'Главный герой',role_key:'hero',hp:850,max_hp:850,damage:12450,ability_name:'Гравитационный разрыв',ability_hint:'Наносит 450% урона и снижает защиту босса',cooldowns:{attack:0,ability:83,heal:0,defend:0}},fighters:[{name:'Илья',role_title:'Гл. герой',hp:850,max_hp:850,damage:12450,is_self:true},{name:'Маша',role_title:'Лекарь',hp:720,max_hp:720,damage:8200},{name:'Саня',role_title:'Дамагер',hp:680,max_hp:680,damage:7700},{name:'Вы',role_title:'Танк',hp:900,max_hp:900,damage:6100}],logs:['Илья задел эго босса на 540 000','Маша восстановила здоровье отряда','Центр Вселенной готовит атаку']};render();tickTimer=setInterval(tick,250); }
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action,b))); ['shop','shopTop'].forEach(id=>$(id).addEventListener('click',()=>openModal())); $('inventory').addEventListener('click',()=>openModal('ИНВЕНТАРЬ','В РАЗРАБОТКЕ')); $('closeModal').addEventListener('click',()=>$('modal').classList.remove('show')); $('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').classList.remove('show')}); document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
  start();
})();
